'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSEDOC_LIQUIDACIONES_COMPRA_LOCAL
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IWSEDOC_LIQUIDACIONES_COMPRA", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSEDOC_LIQUIDACIONES_COMPRA
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarLiquidacionCompraSRIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarLiquidacionCompraSRI_XMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Entidades.My.MySettings.Default.Entidades_WSEDOC_LIQUIDACIONES_COMPRA_WSEDOC_LIQUIDACIONES_COMPRA
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarLiquidacionCompraSRICompleted As EnviarLiquidacionCompraSRICompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarLiquidacionCompraSRI_XMLCompleted As EnviarLiquidacionCompraSRI_XMLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSEDOC_LIQUIDACIONES_COMPRA/EnviarLiquidacionCompraSRI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarLiquidacionCompraSRI(ByVal clave As String, ByVal Entorno As String, ByRef LiquidacionCompra As ENTLiquidacionCompra, ByRef mensaje As String) As RespuestaEDOC
            Dim results() As Object = Me.Invoke("EnviarLiquidacionCompraSRI", New Object() {clave, Entorno, LiquidacionCompra, mensaje})
            LiquidacionCompra = CType(results(1),ENTLiquidacionCompra)
            mensaje = CType(results(2),String)
            Return CType(results(0),RespuestaEDOC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarLiquidacionCompraSRIAsync(ByVal clave As String, ByVal Entorno As String, ByVal LiquidacionCompra As ENTLiquidacionCompra, ByVal mensaje As String)
            Me.EnviarLiquidacionCompraSRIAsync(clave, Entorno, LiquidacionCompra, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarLiquidacionCompraSRIAsync(ByVal clave As String, ByVal Entorno As String, ByVal LiquidacionCompra As ENTLiquidacionCompra, ByVal mensaje As String, ByVal userState As Object)
            If (Me.EnviarLiquidacionCompraSRIOperationCompleted Is Nothing) Then
                Me.EnviarLiquidacionCompraSRIOperationCompleted = AddressOf Me.OnEnviarLiquidacionCompraSRIOperationCompleted
            End If
            Me.InvokeAsync("EnviarLiquidacionCompraSRI", New Object() {clave, Entorno, LiquidacionCompra, mensaje}, Me.EnviarLiquidacionCompraSRIOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarLiquidacionCompraSRIOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarLiquidacionCompraSRICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarLiquidacionCompraSRICompleted(Me, New EnviarLiquidacionCompraSRICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSEDOC_LIQUIDACIONES_COMPRA/EnviarLiquidacionCompraSRI_XML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarLiquidacionCompraSRI_XML(ByVal clave As String, ByVal Entorno As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal LiquidacionCompra() As Byte, ByRef mensaje As String) As RespuestaEDOC
            Dim results() As Object = Me.Invoke("EnviarLiquidacionCompraSRI_XML", New Object() {clave, Entorno, LiquidacionCompra, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),RespuestaEDOC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarLiquidacionCompraSRI_XMLAsync(ByVal clave As String, ByVal Entorno As String, ByVal LiquidacionCompra() As Byte, ByVal mensaje As String)
            Me.EnviarLiquidacionCompraSRI_XMLAsync(clave, Entorno, LiquidacionCompra, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarLiquidacionCompraSRI_XMLAsync(ByVal clave As String, ByVal Entorno As String, ByVal LiquidacionCompra() As Byte, ByVal mensaje As String, ByVal userState As Object)
            If (Me.EnviarLiquidacionCompraSRI_XMLOperationCompleted Is Nothing) Then
                Me.EnviarLiquidacionCompraSRI_XMLOperationCompleted = AddressOf Me.OnEnviarLiquidacionCompraSRI_XMLOperationCompleted
            End If
            Me.InvokeAsync("EnviarLiquidacionCompraSRI_XML", New Object() {clave, Entorno, LiquidacionCompra, mensaje}, Me.EnviarLiquidacionCompraSRI_XMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarLiquidacionCompraSRI_XMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarLiquidacionCompraSRI_XMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarLiquidacionCompraSRI_XMLCompleted(Me, New EnviarLiquidacionCompraSRI_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTLiquidacionCompra
        
        Private tipoField As System.Nullable(Of Integer)
        
        Private eNTLiquidacionCompraPagosField() As ENTLiquidacionCompraPagos
        
        Private eNTLiquidacionCompraReembolsoField() As ENTLiquidacionCompraReembolso
        
        Private dirProveedorField As String
        
        Private campo1Field As String
        
        Private campo2Field As String
        
        Private campo3Field As String
        
        Private campo4Field As String
        
        Private campo5Field As String
        
        Private campo6Field As String
        
        Private campo7Field As String
        
        Private campo8Field As String
        
        Private campo9Field As String
        
        Private campo10Field As String
        
        Private campo11Field As String
        
        Private campo12Field As String
        
        Private campo13Field As String
        
        Private campo14Field As String
        
        Private campo15Field As String
        
        Private codigoTransaccionERPField As String
        
        Private usuarioProcesoField As String
        
        Private usuarioTransaccionERPField As String
        
        Private idLiquidacionCompraField As Long
        
        Private autorizacionSRIField As String
        
        Private fechaAutorizacionField As System.Nullable(Of Date)
        
        Private ambienteField As Integer
        
        Private tipoEmisionField As Integer
        
        Private razonSocialField As String
        
        Private nombreComercialField As String
        
        Private rucField As String
        
        Private claveAccesoField As String
        
        Private codigoDocumentoField As String
        
        Private establecimientoField As String
        
        Private puntoEmisionField As String
        
        Private secuencialField As String
        
        Private direccionMatrizField As String
        
        Private fechaEmisionField As Date
        
        Private direccionEstablecimientoField As String
        
        Private contribuyenteEspecialField As String
        
        Private obligadoContabilidadField As String
        
        Private tipoIdentificacionProveedorField As String
        
        Private razonSocialProveedorField As String
        
        Private identificacionProveedorField As String
        
        Private totalSinImpuestoField As Decimal
        
        Private totalDescuentoField As Decimal
        
        Private codDocReembField As String
        
        Private totalComprobantesReembolsoField As System.Nullable(Of Decimal)
        
        Private totalBaseImponibleReembolsoField As System.Nullable(Of Decimal)
        
        Private totalImpuestoReembolsoField As System.Nullable(Of Decimal)
        
        Private importeTotalField As Decimal
        
        Private monedaField As String
        
        Private estadoField As Integer
        
        Private secuencialERPField As String
        
        Private eNTLiquidacionCompraImpuestoField() As ENTLiquidacionCompraImpuesto
        
        Private eNTDatoAdicionalLiquidacionCompraField() As ENTDatoAdicionalLiquidacionCompra
        
        Private emailResponsableField As String
        
        Private fechaCargaField As String
        
        Private eNTDetalleLiquidacionCompraField() As ENTDetalleLiquidacionCompra
        
        Private datosFacturadorManualField As DatosFacturadorManual
        
        Private claveCertificadoField As String
        
        Private nombreArchivoField As String
        
        Private eNTDatosOpcionalesField As ENTDatosOpcionales
        
        Private nombreIntegracionField As String
        
        Private ipField As String
        
        Private eNTMaquinaFiscalField As ENTMaquinaFiscal
        
        Private regimenMicroempresasField As System.Nullable(Of Boolean)
        
        Private agenteRetencionField As System.Nullable(Of Integer)
        
        Private contribuyenteRimpeField As System.Nullable(Of Boolean)
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Tipo() As System.Nullable(Of Integer)
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTLiquidacionCompraPagos() As ENTLiquidacionCompraPagos()
            Get
                Return Me.eNTLiquidacionCompraPagosField
            End Get
            Set
                Me.eNTLiquidacionCompraPagosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTLiquidacionCompraReembolso() As ENTLiquidacionCompraReembolso()
            Get
                Return Me.eNTLiquidacionCompraReembolsoField
            End Get
            Set
                Me.eNTLiquidacionCompraReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirProveedor() As String
            Get
                Return Me.dirProveedorField
            End Get
            Set
                Me.dirProveedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo1() As String
            Get
                Return Me.campo1Field
            End Get
            Set
                Me.campo1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo2() As String
            Get
                Return Me.campo2Field
            End Get
            Set
                Me.campo2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo3() As String
            Get
                Return Me.campo3Field
            End Get
            Set
                Me.campo3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo4() As String
            Get
                Return Me.campo4Field
            End Get
            Set
                Me.campo4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo5() As String
            Get
                Return Me.campo5Field
            End Get
            Set
                Me.campo5Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo6() As String
            Get
                Return Me.campo6Field
            End Get
            Set
                Me.campo6Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo7() As String
            Get
                Return Me.campo7Field
            End Get
            Set
                Me.campo7Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo8() As String
            Get
                Return Me.campo8Field
            End Get
            Set
                Me.campo8Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo9() As String
            Get
                Return Me.campo9Field
            End Get
            Set
                Me.campo9Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo10() As String
            Get
                Return Me.campo10Field
            End Get
            Set
                Me.campo10Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo11() As String
            Get
                Return Me.campo11Field
            End Get
            Set
                Me.campo11Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo12() As String
            Get
                Return Me.campo12Field
            End Get
            Set
                Me.campo12Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo13() As String
            Get
                Return Me.campo13Field
            End Get
            Set
                Me.campo13Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo14() As String
            Get
                Return Me.campo14Field
            End Get
            Set
                Me.campo14Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo15() As String
            Get
                Return Me.campo15Field
            End Get
            Set
                Me.campo15Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoTransaccionERP() As String
            Get
                Return Me.codigoTransaccionERPField
            End Get
            Set
                Me.codigoTransaccionERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioProceso() As String
            Get
                Return Me.usuarioProcesoField
            End Get
            Set
                Me.usuarioProcesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioTransaccionERP() As String
            Get
                Return Me.usuarioTransaccionERPField
            End Get
            Set
                Me.usuarioTransaccionERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdLiquidacionCompra() As Long
            Get
                Return Me.idLiquidacionCompraField
            End Get
            Set
                Me.idLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AutorizacionSRI() As String
            Get
                Return Me.autorizacionSRIField
            End Get
            Set
                Me.autorizacionSRIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaAutorizacion() As System.Nullable(Of Date)
            Get
                Return Me.fechaAutorizacionField
            End Get
            Set
                Me.fechaAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ambiente() As Integer
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoEmision() As Integer
            Get
                Return Me.tipoEmisionField
            End Get
            Set
                Me.tipoEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreComercial() As String
            Get
                Return Me.nombreComercialField
            End Get
            Set
                Me.nombreComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ruc() As String
            Get
                Return Me.rucField
            End Get
            Set
                Me.rucField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoDocumento() As String
            Get
                Return Me.codigoDocumentoField
            End Get
            Set
                Me.codigoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Establecimiento() As String
            Get
                Return Me.establecimientoField
            End Get
            Set
                Me.establecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PuntoEmision() As String
            Get
                Return Me.puntoEmisionField
            End Get
            Set
                Me.puntoEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Secuencial() As String
            Get
                Return Me.secuencialField
            End Get
            Set
                Me.secuencialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionMatriz() As String
            Get
                Return Me.direccionMatrizField
            End Get
            Set
                Me.direccionMatrizField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEmision() As Date
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                Me.fechaEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionEstablecimiento() As String
            Get
                Return Me.direccionEstablecimientoField
            End Get
            Set
                Me.direccionEstablecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContribuyenteEspecial() As String
            Get
                Return Me.contribuyenteEspecialField
            End Get
            Set
                Me.contribuyenteEspecialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObligadoContabilidad() As String
            Get
                Return Me.obligadoContabilidadField
            End Get
            Set
                Me.obligadoContabilidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificacionProveedor() As String
            Get
                Return Me.tipoIdentificacionProveedorField
            End Get
            Set
                Me.tipoIdentificacionProveedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocialProveedor() As String
            Get
                Return Me.razonSocialProveedorField
            End Get
            Set
                Me.razonSocialProveedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionProveedor() As String
            Get
                Return Me.identificacionProveedorField
            End Get
            Set
                Me.identificacionProveedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalSinImpuesto() As Decimal
            Get
                Return Me.totalSinImpuestoField
            End Get
            Set
                Me.totalSinImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalDescuento() As Decimal
            Get
                Return Me.totalDescuentoField
            End Get
            Set
                Me.totalDescuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodDocReemb() As String
            Get
                Return Me.codDocReembField
            End Get
            Set
                Me.codDocReembField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalComprobantesReembolso() As System.Nullable(Of Decimal)
            Get
                Return Me.totalComprobantesReembolsoField
            End Get
            Set
                Me.totalComprobantesReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalBaseImponibleReembolso() As System.Nullable(Of Decimal)
            Get
                Return Me.totalBaseImponibleReembolsoField
            End Get
            Set
                Me.totalBaseImponibleReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalImpuestoReembolso() As System.Nullable(Of Decimal)
            Get
                Return Me.totalImpuestoReembolsoField
            End Get
            Set
                Me.totalImpuestoReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImporteTotal() As Decimal
            Get
                Return Me.importeTotalField
            End Get
            Set
                Me.importeTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As Integer
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecuencialERP() As String
            Get
                Return Me.secuencialERPField
            End Get
            Set
                Me.secuencialERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTLiquidacionCompraImpuesto() As ENTLiquidacionCompraImpuesto()
            Get
                Return Me.eNTLiquidacionCompraImpuestoField
            End Get
            Set
                Me.eNTLiquidacionCompraImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatoAdicionalLiquidacionCompra() As ENTDatoAdicionalLiquidacionCompra()
            Get
                Return Me.eNTDatoAdicionalLiquidacionCompraField
            End Get
            Set
                Me.eNTDatoAdicionalLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailResponsable() As String
            Get
                Return Me.emailResponsableField
            End Get
            Set
                Me.emailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaCarga() As String
            Get
                Return Me.fechaCargaField
            End Get
            Set
                Me.fechaCargaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDetalleLiquidacionCompra() As ENTDetalleLiquidacionCompra()
            Get
                Return Me.eNTDetalleLiquidacionCompraField
            End Get
            Set
                Me.eNTDetalleLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatosFacturadorManual() As DatosFacturadorManual
            Get
                Return Me.datosFacturadorManualField
            End Get
            Set
                Me.datosFacturadorManualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveCertificado() As String
            Get
                Return Me.claveCertificadoField
            End Get
            Set
                Me.claveCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreArchivo() As String
            Get
                Return Me.nombreArchivoField
            End Get
            Set
                Me.nombreArchivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatosOpcionales() As ENTDatosOpcionales
            Get
                Return Me.eNTDatosOpcionalesField
            End Get
            Set
                Me.eNTDatosOpcionalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreIntegracion() As String
            Get
                Return Me.nombreIntegracionField
            End Get
            Set
                Me.nombreIntegracionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IP() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTMaquinaFiscal() As ENTMaquinaFiscal
            Get
                Return Me.eNTMaquinaFiscalField
            End Get
            Set
                Me.eNTMaquinaFiscalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RegimenMicroempresas() As System.Nullable(Of Boolean)
            Get
                Return Me.regimenMicroempresasField
            End Get
            Set
                Me.regimenMicroempresasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AgenteRetencion() As System.Nullable(Of Integer)
            Get
                Return Me.agenteRetencionField
            End Get
            Set
                Me.agenteRetencionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ContribuyenteRimpe() As System.Nullable(Of Boolean)
            Get
                Return Me.contribuyenteRimpeField
            End Get
            Set
                Me.contribuyenteRimpeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTLiquidacionCompraPagos
        
        Private formaPagoField As String
        
        Private totalField As Decimal
        
        Private plazoField As System.Nullable(Of Integer)
        
        Private unidadTiempoField As String
        
        '''<remarks/>
        Public Property FormaPago() As String
            Get
                Return Me.formaPagoField
            End Get
            Set
                Me.formaPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Plazo() As System.Nullable(Of Integer)
            Get
                Return Me.plazoField
            End Get
            Set
                Me.plazoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnidadTiempo() As String
            Get
                Return Me.unidadTiempoField
            End Get
            Set
                Me.unidadTiempoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EComprobante
        
        Private claveAccesoField As String
        
        Private mensajesField() As EMensaje
        
        '''<remarks/>
        Public Property claveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensajes() As EMensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EMensaje
        
        Private identificadorField As String
        
        Private mensaje1Field As String
        
        Private informacionAdicionalField As String
        
        Private tipoField As String
        
        '''<remarks/>
        Public Property identificador() As String
            Get
                Return Me.identificadorField
            End Get
            Set
                Me.identificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje1() As String
            Get
                Return Me.mensaje1Field
            End Get
            Set
                Me.mensaje1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property informacionAdicional() As String
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                Me.informacionAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EAutorizacion
        
        Private estadoField As String
        
        Private numeroAutorizacionField As String
        
        Private claveAccesoField As String
        
        Private fechaAutorizacionField As Date
        
        Private fechaAutorizacionFieldSpecified As Boolean
        
        Private fechaAutorizacionSpecified1Field As Boolean
        
        Private ambienteField As String
        
        Private comprobanteField As String
        
        Private mensajesField() As EMensaje
        
        '''<remarks/>
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroAutorizacion() As String
            Get
                Return Me.numeroAutorizacionField
            End Get
            Set
                Me.numeroAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fechaAutorizacion() As Date
            Get
                Return Me.fechaAutorizacionField
            End Get
            Set
                Me.fechaAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaAutorizacionSpecified() As Boolean
            Get
                Return Me.fechaAutorizacionFieldSpecified
            End Get
            Set
                Me.fechaAutorizacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("fechaAutorizacionSpecified")>  _
        Public Property fechaAutorizacionSpecified1() As Boolean
            Get
                Return Me.fechaAutorizacionSpecified1Field
            End Get
            Set
                Me.fechaAutorizacionSpecified1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ambiente() As String
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comprobante() As String
            Get
                Return Me.comprobanteField
            End Get
            Set
                Me.comprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensajes() As EMensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaEDOC
        
        Private claveAccesoField As String
        
        Private numeroComprobantesField As String
        
        Private estadoField As String
        
        Private autorizacionesField() As EAutorizacion
        
        Private comprobantesField() As EComprobante
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroComprobantes() As String
            Get
                Return Me.numeroComprobantesField
            End Get
            Set
                Me.numeroComprobantesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property autorizaciones() As EAutorizacion()
            Get
                Return Me.autorizacionesField
            End Get
            Set
                Me.autorizacionesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comprobantes() As EComprobante()
            Get
                Return Me.comprobantesField
            End Get
            Set
                Me.comprobantesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTMaquinaFiscal
        
        Private marcaField As String
        
        Private modeloField As String
        
        Private serieField As String
        
        '''<remarks/>
        Public Property Marca() As String
            Get
                Return Me.marcaField
            End Get
            Set
                Me.marcaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Modelo() As String
            Get
                Return Me.modeloField
            End Get
            Set
                Me.modeloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatosOpcionales
        
        Private mailResponsableField As String
        
        Private usuarioCreadorField As String
        
        Private directorioDocumentoField As String
        
        Private nombreDocumentoField As String
        
        '''<remarks/>
        Public Property MailResponsable() As String
            Get
                Return Me.mailResponsableField
            End Get
            Set
                Me.mailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioCreador() As String
            Get
                Return Me.usuarioCreadorField
            End Get
            Set
                Me.usuarioCreadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirectorioDocumento() As String
            Get
                Return Me.directorioDocumentoField
            End Get
            Set
                Me.directorioDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreDocumento() As String
            Get
                Return Me.nombreDocumentoField
            End Get
            Set
                Me.nombreDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DatosFacturadorManual
        
        Private facturadorManualField As Boolean
        
        Private usaDirectorioField As Integer
        
        '''<remarks/>
        Public Property FacturadorManual() As Boolean
            Get
                Return Me.facturadorManualField
            End Get
            Set
                Me.facturadorManualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaDirectorio() As Integer
            Get
                Return Me.usaDirectorioField
            End Get
            Set
                Me.usaDirectorioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDetalleLiquidacionCompraImpuesto
        
        Private idDetalleLiquidacionCompraImpuestoField As Long
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private baseImponibleField As Decimal
        
        Private tarifaField As Decimal
        
        Private valorField As Decimal
        
        Private idDetalleLiquidacionCompraField As Long
        
        '''<remarks/>
        Public Property IdDetalleLiquidacionCompraImpuesto() As Long
            Get
                Return Me.idDetalleLiquidacionCompraImpuestoField
            End Get
            Set
                Me.idDetalleLiquidacionCompraImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseImponible() As Decimal
            Get
                Return Me.baseImponibleField
            End Get
            Set
                Me.baseImponibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Decimal
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdDetalleLiquidacionCompra() As Long
            Get
                Return Me.idDetalleLiquidacionCompraField
            End Get
            Set
                Me.idDetalleLiquidacionCompraField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatoAdicionalDetalleLiquidacionCompra
        
        Private idDatoAdicionalDetalleLiquidacionCompraField As Long
        
        Private nombreField As String
        
        Private descripcionField As String
        
        Private idDetalleLiquidacionCompraField As Long
        
        '''<remarks/>
        Public Property IdDatoAdicionalDetalleLiquidacionCompra() As Long
            Get
                Return Me.idDatoAdicionalDetalleLiquidacionCompraField
            End Get
            Set
                Me.idDatoAdicionalDetalleLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdDetalleLiquidacionCompra() As Long
            Get
                Return Me.idDetalleLiquidacionCompraField
            End Get
            Set
                Me.idDetalleLiquidacionCompraField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDetalleLiquidacionCompra
        
        Private idDetalleLiquidacionCompraField As Long
        
        Private codigoPrincipalField As String
        
        Private codigoAuxiliarField As String
        
        Private descripcionField As String
        
        Private unidadMedidaField As String
        
        Private cantidadField As Decimal
        
        Private precioUnitarioField As Decimal
        
        Private descuentoField As System.Nullable(Of Decimal)
        
        Private precioTotalSinImpuestoField As Decimal
        
        Private idLiquidacionCompraField As Long
        
        Private eNTDatoAdicionalDetalleLiquidacionCompraField() As ENTDatoAdicionalDetalleLiquidacionCompra
        
        Private eNTDetalleLiquidacionCompraImpuestoField() As ENTDetalleLiquidacionCompraImpuesto
        
        '''<remarks/>
        Public Property IdDetalleLiquidacionCompra() As Long
            Get
                Return Me.idDetalleLiquidacionCompraField
            End Get
            Set
                Me.idDetalleLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPrincipal() As String
            Get
                Return Me.codigoPrincipalField
            End Get
            Set
                Me.codigoPrincipalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoAuxiliar() As String
            Get
                Return Me.codigoAuxiliarField
            End Get
            Set
                Me.codigoAuxiliarField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnidadMedida() As String
            Get
                Return Me.unidadMedidaField
            End Get
            Set
                Me.unidadMedidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioUnitario() As Decimal
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Descuento() As System.Nullable(Of Decimal)
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioTotalSinImpuesto() As Decimal
            Get
                Return Me.precioTotalSinImpuestoField
            End Get
            Set
                Me.precioTotalSinImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdLiquidacionCompra() As Long
            Get
                Return Me.idLiquidacionCompraField
            End Get
            Set
                Me.idLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatoAdicionalDetalleLiquidacionCompra() As ENTDatoAdicionalDetalleLiquidacionCompra()
            Get
                Return Me.eNTDatoAdicionalDetalleLiquidacionCompraField
            End Get
            Set
                Me.eNTDatoAdicionalDetalleLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDetalleLiquidacionCompraImpuesto() As ENTDetalleLiquidacionCompraImpuesto()
            Get
                Return Me.eNTDetalleLiquidacionCompraImpuestoField
            End Get
            Set
                Me.eNTDetalleLiquidacionCompraImpuestoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatoAdicionalLiquidacionCompra
        
        Private idDatoAdicionalLiquidacionCompraField As Long
        
        Private nombreField As String
        
        Private descripcionField As String
        
        Private idLiquidacionCompraField As Long
        
        '''<remarks/>
        Public Property IdDatoAdicionalLiquidacionCompra() As Long
            Get
                Return Me.idDatoAdicionalLiquidacionCompraField
            End Get
            Set
                Me.idDatoAdicionalLiquidacionCompraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdLiquidacionCompra() As Long
            Get
                Return Me.idLiquidacionCompraField
            End Get
            Set
                Me.idLiquidacionCompraField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTLiquidacionCompraImpuesto
        
        Private descuentoAdicionalField As System.Nullable(Of Decimal)
        
        Private idLiquidacionCompraImpuestoField As Long
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private baseImponibleField As Decimal
        
        Private tarifaField As Decimal
        
        Private valorField As Decimal
        
        Private idLiquidacionCompraField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DescuentoAdicional() As System.Nullable(Of Decimal)
            Get
                Return Me.descuentoAdicionalField
            End Get
            Set
                Me.descuentoAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdLiquidacionCompraImpuesto() As Long
            Get
                Return Me.idLiquidacionCompraImpuestoField
            End Get
            Set
                Me.idLiquidacionCompraImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseImponible() As Decimal
            Get
                Return Me.baseImponibleField
            End Get
            Set
                Me.baseImponibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Decimal
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdLiquidacionCompra() As Long
            Get
                Return Me.idLiquidacionCompraField
            End Get
            Set
                Me.idLiquidacionCompraField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTLiquidacionCompraReembolsoImpuesto
        
        Private idLiquidacionCompraImpuestoField As Long
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private baseImponibleReembolsoField As Decimal
        
        Private tarifaField As Long
        
        Private impuestoReembolsoField As Decimal
        
        Private idReembolsoField As Long
        
        '''<remarks/>
        Public Property IdLiquidacionCompraImpuesto() As Long
            Get
                Return Me.idLiquidacionCompraImpuestoField
            End Get
            Set
                Me.idLiquidacionCompraImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseImponibleReembolso() As Decimal
            Get
                Return Me.baseImponibleReembolsoField
            End Get
            Set
                Me.baseImponibleReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Long
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImpuestoReembolso() As Decimal
            Get
                Return Me.impuestoReembolsoField
            End Get
            Set
                Me.impuestoReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdReembolso() As Long
            Get
                Return Me.idReembolsoField
            End Get
            Set
                Me.idReembolsoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTLiquidacionCompraReembolso
        
        Private eNTLiquidacionCompraReembolsoImpuestosField() As ENTLiquidacionCompraReembolsoImpuesto
        
        Private idReembolsoField As Long
        
        Private tipoIdentificacionProveedorReembolsoField As String
        
        Private identificacionProveedorReembolsoField As String
        
        Private codPaisPagoProveedorReembolsoField As Integer
        
        Private tipoProveedorReembolsoField As String
        
        Private codDocReembolsoField As String
        
        Private estabDocReembolsoField As String
        
        Private ptoEmiDocReembolsoField As String
        
        Private secuencialDocReembolsoField As String
        
        Private fechaEmisionDocReembolsoField As Date
        
        Private numeroAutorizacionDocReembField As String
        
        '''<remarks/>
        Public Property ENTLiquidacionCompraReembolsoImpuestos() As ENTLiquidacionCompraReembolsoImpuesto()
            Get
                Return Me.eNTLiquidacionCompraReembolsoImpuestosField
            End Get
            Set
                Me.eNTLiquidacionCompraReembolsoImpuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdReembolso() As Long
            Get
                Return Me.idReembolsoField
            End Get
            Set
                Me.idReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificacionProveedorReembolso() As String
            Get
                Return Me.tipoIdentificacionProveedorReembolsoField
            End Get
            Set
                Me.tipoIdentificacionProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionProveedorReembolso() As String
            Get
                Return Me.identificacionProveedorReembolsoField
            End Get
            Set
                Me.identificacionProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodPaisPagoProveedorReembolso() As Integer
            Get
                Return Me.codPaisPagoProveedorReembolsoField
            End Get
            Set
                Me.codPaisPagoProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoProveedorReembolso() As String
            Get
                Return Me.tipoProveedorReembolsoField
            End Get
            Set
                Me.tipoProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodDocReembolso() As String
            Get
                Return Me.codDocReembolsoField
            End Get
            Set
                Me.codDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstabDocReembolso() As String
            Get
                Return Me.estabDocReembolsoField
            End Get
            Set
                Me.estabDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PtoEmiDocReembolso() As String
            Get
                Return Me.ptoEmiDocReembolsoField
            End Get
            Set
                Me.ptoEmiDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecuencialDocReembolso() As String
            Get
                Return Me.secuencialDocReembolsoField
            End Get
            Set
                Me.secuencialDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEmisionDocReembolso() As Date
            Get
                Return Me.fechaEmisionDocReembolsoField
            End Get
            Set
                Me.fechaEmisionDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroAutorizacionDocReemb() As String
            Get
                Return Me.numeroAutorizacionDocReembField
            End Get
            Set
                Me.numeroAutorizacionDocReembField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub EnviarLiquidacionCompraSRICompletedEventHandler(ByVal sender As Object, ByVal e As EnviarLiquidacionCompraSRICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarLiquidacionCompraSRICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEDOC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEDOC)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property LiquidacionCompra() As ENTLiquidacionCompra
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),ENTLiquidacionCompra)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub EnviarLiquidacionCompraSRI_XMLCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarLiquidacionCompraSRI_XMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarLiquidacionCompraSRI_XMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEDOC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEDOC)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
