'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsSS_LICENCIA_SAP
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_ILicencia", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Licencia
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ValidarClaveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidarLicenciaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarParametrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Entidades.My.MySettings.Default.Entidades_wsSS_LICENCIA_SAP_Licencia
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ValidarClaveCompleted As ValidarClaveCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidarLicenciaCompleted As ValidarLicenciaCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarParametrosCompleted As ConsultarParametrosCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILicencia/ValidarClave", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidarClave(ByVal cre As Credencial, ByRef mensaje As String) As Boolean
            Dim results() As Object = Me.Invoke("ValidarClave", New Object() {cre, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidarClaveAsync(ByVal cre As Credencial, ByVal mensaje As String)
            Me.ValidarClaveAsync(cre, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidarClaveAsync(ByVal cre As Credencial, ByVal mensaje As String, ByVal userState As Object)
            If (Me.ValidarClaveOperationCompleted Is Nothing) Then
                Me.ValidarClaveOperationCompleted = AddressOf Me.OnValidarClaveOperationCompleted
            End If
            Me.InvokeAsync("ValidarClave", New Object() {cre, mensaje}, Me.ValidarClaveOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidarClaveOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidarClaveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidarClaveCompleted(Me, New ValidarClaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILicencia/ValidarLicencia", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidarLicencia(ByVal dato As DatosSap, ByRef Mensaje As String) As CLsRespLic
            Dim results() As Object = Me.Invoke("ValidarLicencia", New Object() {dato, Mensaje})
            Mensaje = CType(results(1),String)
            Return CType(results(0),CLsRespLic)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidarLicenciaAsync(ByVal dato As DatosSap, ByVal Mensaje As String)
            Me.ValidarLicenciaAsync(dato, Mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidarLicenciaAsync(ByVal dato As DatosSap, ByVal Mensaje As String, ByVal userState As Object)
            If (Me.ValidarLicenciaOperationCompleted Is Nothing) Then
                Me.ValidarLicenciaOperationCompleted = AddressOf Me.OnValidarLicenciaOperationCompleted
            End If
            Me.InvokeAsync("ValidarLicencia", New Object() {dato, Mensaje}, Me.ValidarLicenciaOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidarLicenciaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidarLicenciaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidarLicenciaCompleted(Me, New ValidarLicenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILicencia/ConsultarParametros", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarParametros(ByVal modulo As String, ByVal tipo As String, ByVal subtipo As String, ByRef Mensaje As String) As ClsConfigValores()
            Dim results() As Object = Me.Invoke("ConsultarParametros", New Object() {modulo, tipo, subtipo, Mensaje})
            Mensaje = CType(results(1),String)
            Return CType(results(0),ClsConfigValores())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarParametrosAsync(ByVal modulo As String, ByVal tipo As String, ByVal subtipo As String, ByVal Mensaje As String)
            Me.ConsultarParametrosAsync(modulo, tipo, subtipo, Mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarParametrosAsync(ByVal modulo As String, ByVal tipo As String, ByVal subtipo As String, ByVal Mensaje As String, ByVal userState As Object)
            If (Me.ConsultarParametrosOperationCompleted Is Nothing) Then
                Me.ConsultarParametrosOperationCompleted = AddressOf Me.OnConsultarParametrosOperationCompleted
            End If
            Me.InvokeAsync("ConsultarParametros", New Object() {modulo, tipo, subtipo, Mensaje}, Me.ConsultarParametrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarParametrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarParametrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarParametrosCompleted(Me, New ConsultarParametrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Credencial
        
        Private nombreAddonField As String
        
        Private versionAddonField As String
        
        Private usuarioField As String
        
        Private claveField As String
        
        Private paisField As String
        
        Private nombreClienteField As String
        
        Private nombreBDField As String
        
        Private iPLocalField As String
        
        Private iPPublicaField As String
        
        Private motivoIngresoField As String
        
        '''<remarks/>
        Public Property NombreAddon() As String
            Get
                Return Me.nombreAddonField
            End Get
            Set
                Me.nombreAddonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VersionAddon() As String
            Get
                Return Me.versionAddonField
            End Get
            Set
                Me.versionAddonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                Me.nombreClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreBD() As String
            Get
                Return Me.nombreBDField
            End Get
            Set
                Me.nombreBDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IPLocal() As String
            Get
                Return Me.iPLocalField
            End Get
            Set
                Me.iPLocalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IPPublica() As String
            Get
                Return Me.iPPublicaField
            End Get
            Set
                Me.iPPublicaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MotivoIngreso() As String
            Get
                Return Me.motivoIngresoField
            End Get
            Set
                Me.motivoIngresoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClsConfigValores
        
        Private idLineaField As Long
        
        Private nombreField As String
        
        Private valorField As String
        
        '''<remarks/>
        Public Property IdLinea() As Long
            Get
                Return Me.idLineaField
            End Get
            Set
                Me.idLineaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CLsRespLic
        
        Private estadoField As Boolean
        
        Private tipoLicField As String
        
        Private mailResponsableField As String
        
        Private versionTributariaField As String
        
        Private listaUrlWSField() As ClsConfigValores
        
        Private versionProductoField As String
        
        Private releaseNoteProductoField As String
        
        Private tipoRecepcionField As String
        
        '''<remarks/>
        Public Property Estado() As Boolean
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoLic() As String
            Get
                Return Me.tipoLicField
            End Get
            Set
                Me.tipoLicField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MailResponsable() As String
            Get
                Return Me.mailResponsableField
            End Get
            Set
                Me.mailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VersionTributaria() As String
            Get
                Return Me.versionTributariaField
            End Get
            Set
                Me.versionTributariaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListaUrlWS() As ClsConfigValores()
            Get
                Return Me.listaUrlWSField
            End Get
            Set
                Me.listaUrlWSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VersionProducto() As String
            Get
                Return Me.versionProductoField
            End Get
            Set
                Me.versionProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReleaseNoteProducto() As String
            Get
                Return Me.releaseNoteProductoField
            End Get
            Set
                Me.releaseNoteProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoRecepcion() As String
            Get
                Return Me.tipoRecepcionField
            End Get
            Set
                Me.tipoRecepcionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DatosSap
        
        Private rucEmpresaField As String
        
        Private nombreProductoField As String
        
        Private nombreDBField As String
        
        Private direccionIPSERVERField As String
        
        Private versionProductoField As String
        
        Private ambienteField As Integer
        
        Private inhouseField As Boolean
        
        '''<remarks/>
        Public Property RucEmpresa() As String
            Get
                Return Me.rucEmpresaField
            End Get
            Set
                Me.rucEmpresaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreProducto() As String
            Get
                Return Me.nombreProductoField
            End Get
            Set
                Me.nombreProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreDB() As String
            Get
                Return Me.nombreDBField
            End Get
            Set
                Me.nombreDBField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionIPSERVER() As String
            Get
                Return Me.direccionIPSERVERField
            End Get
            Set
                Me.direccionIPSERVERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VersionProducto() As String
            Get
                Return Me.versionProductoField
            End Get
            Set
                Me.versionProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ambiente() As Integer
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Inhouse() As Boolean
            Get
                Return Me.inhouseField
            End Get
            Set
                Me.inhouseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ValidarClaveCompletedEventHandler(ByVal sender As Object, ByVal e As ValidarClaveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidarClaveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ValidarLicenciaCompletedEventHandler(ByVal sender As Object, ByVal e As ValidarLicenciaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidarLicenciaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CLsRespLic
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CLsRespLic)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ConsultarParametrosCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarParametrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarParametrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ClsConfigValores()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ClsConfigValores())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
