<?xml version="1.0" encoding="utf-8"?>
<AddOnRegData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" SlientInstallation="No" SlientUpgrade="No" Partnernmsp="SOLSAP S.A" SchemaVersion="3.0" Type="" MultipleVersion="false" OnDemand="" OnPremise="" ExtName="SAED PLUS LW 9.2" ExtVersion="3.9.1.2.7" Contdata="info@soluciones-sap.com" Partner="SOLSAP S.A" DBType="Both" ClientType="A">
  <Validity>
    <SBOCompatibility>
      <Version From="920.200.00" To="1000.250.00" />
    </SBOCompatibility>
  </Validity>
  <Configuration>
    <Repository>
      <Properties />
    </Repository>
    <Deployment>
      <Properties />
    </Deployment>
    <Assignment>
      <Properties />
    </Assignment>
  </Configuration>
  <Addons>
    <Addon Name="" Group="" ForceFlag="" Visible="" AutoAssign="" SelfUpgrd="">
      <x86 AddonExe="" AddonSig="">
        <Installation>
          <Files />
        </Installation>
        <Uninstallation>
          <Files />
        </Uninstallation>
      </x86>
      <x64 AddonExe="C:\Users\William\Desktop\ADD-ONS SOLSAP\FE\LOCALIZACION-SAED-Calidad\Servicio Ivend\bin\x64\Debug\SS_ProcesadorFE.exe" AddonSig="">
        <Installation>
          <Files>
            <File FileName="Entidades.dll">
              <Actions />
            </File>
            <File FileName="Functions.dll">
              <Actions />
            </File>
            <File FileName="Microsoft.mshtml.dll">
              <Actions />
            </File>
            <File FileName="Negocio.dll">
              <Actions />
            </File>
            <File FileName="Newtonsoft.Json.dll">
              <Actions />
            </File>
            <File FileName="Spire.License.dll">
              <Actions />
            </File>
            <File FileName="Spire.Pdf.dll">
              <Actions />
            </File>
            <File FileName="SS_ProcesadorFE.exe">
              <Actions />
            </File>
            <File FileName="Utilitario.dll">
              <Actions />
            </File>
            <File FileName="zxing.dll">
              <Actions />
            </File>
          </Files>
        </Installation>
        <Uninstallation>
          <Files>
            <File FileName="Entidades.dll">
              <Actions />
            </File>
            <File FileName="Functions.dll">
              <Actions />
            </File>
            <File FileName="Microsoft.mshtml.dll">
              <Actions />
            </File>
            <File FileName="Negocio.dll">
              <Actions />
            </File>
            <File FileName="Newtonsoft.Json.dll">
              <Actions />
            </File>
            <File FileName="Spire.License.dll">
              <Actions />
            </File>
            <File FileName="Spire.Pdf.dll">
              <Actions />
            </File>
            <File FileName="SS_ProcesadorFE.exe">
              <Actions />
            </File>
            <File FileName="Utilitario.dll">
              <Actions />
            </File>
            <File FileName="zxing.dll">
              <Actions />
            </File>
          </Files>
        </Uninstallation>
      </x64>
    </Addon>
  </Addons>
  <XApps>
    <XApp Name="" Path="" FileName="" />
  </XApps>
  <UDQs>
    <UDQ udqname="">
      <Hana FileName="" />
    </UDQ>
  </UDQs>
</AddOnRegData>