'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("slnGSEDOC_SAP_EC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 01;SIN UTILIZACION DEL SISTEMA FINANCIERO
        '''02;CHEQUE PROPIO
        '''03;CHEQUE CERTIFICADO
        '''04;CHEQUE DE GERENCIA
        '''05;CHEQUE DEL EXTERIOR
        '''06;DÉBITO DE CUENTA
        '''07;TRANSFERENCIA PROPIO BANCO
        '''08;TRANSFERENCIA OTRO BANCO NACIONAL
        '''09;TRANSFERENCIA OTRO BANCO NACIONAL
        '''10;TARJETA DE CRÉDITO NACIONAL
        '''11;TARJETA DE CRÉDITO INTERNACIONAL
        '''12;GIRO
        '''13;DEPOSITO EN CUENTA (CORRIENTE/AHORROS)
        '''14;ENDOSO DE INVERSIÒN
        '''15;COMPENSACIÓN DE DEUDAS
        '''16;TARJETA DE DÉBITO
        '''17;DINERO ELECTRÓNICO
        '''18;TARJETA PREPAGO
        '''20;CON UTILIZACION DEL SISTEMA FIN [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property FORMASDEPAGO() As String
            Get
                Return ResourceManager.GetString("FORMASDEPAGO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &quot;FormatCode&quot;, &quot;AcctName&quot; FROM OACT WHERE &quot;Levels&quot; = 5.
        '''</summary>
        Friend ReadOnly Property GetCuentasServicios() As String
            Get
                Return ResourceManager.GetString("GetCuentasServicios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select &quot;Code&quot;, &quot;Name&quot; from OSTC Where &quot;ValidForAP&quot; = &apos;Y&apos;.
        '''</summary>
        Friend ReadOnly Property GetIndicadoresImpuestos() As String
            Get
                Return ResourceManager.GetString("GetIndicadoresImpuestos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT T0.&quot;CreditCard&quot;,T0.&quot;CardName&quot; FROM OCRC T0.
        '''</summary>
        Friend ReadOnly Property GetTartejaCredito() As String
            Get
                Return ResourceManager.GetString("GetTartejaCredito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT T0.&quot;SeriesName&quot;,T0.&quot;Remark&quot;
        '''  FROM NNM1 T0
        '''WHERE T0.&quot;Remark&quot; !=&apos;&apos;.
        '''</summary>
        Friend ReadOnly Property SERIESDOCUMENTO_HANA() As String
            Get
                Return ResourceManager.GetString("SERIESDOCUMENTO_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT T0.SERIESNAME,T0.REMARK
        '''  FROM [dbo].[NNM1] T0
        '''WHERE T0.REMARK !=&apos;&apos;.
        '''</summary>
        Friend ReadOnly Property SERIESDOCUMENTOS_SQL() As String
            Get
                Return ResourceManager.GetString("SERIESDOCUMENTOS_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 2021;2021
        '''2022;2022
        '''2023;2023
        '''2024;2024
        '''2025;2025.
        '''</summary>
        Friend ReadOnly Property SS_ANIO() As String
            Get
                Return ResourceManager.GetString("SS_ANIO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &quot;U_SS_CodPais&quot; as Codigo, &quot;U_SS_NomPais&quot; as Nombre FROM &quot;@SS_PAISES&quot; ORDER BY cast(&quot;Code&quot; as int).
        '''</summary>
        Friend ReadOnly Property SS_BF_PAISES() As String
            Get
                Return ResourceManager.GetString("SS_BF_PAISES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a U_SS_Est
        '''U_SS_Pemi
        '''U_SS_FormaPagos.
        '''</summary>
        Friend ReadOnly Property SS_CAMPOS_FACTURA_VENTA() As String
            Get
                Return ResourceManager.GetString("SS_CAMPOS_FACTURA_VENTA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE PROVINCIA VARCHAR(100);
        '''DECLARE CANTON VARCHAR(100);
        '''SELECT (SELECT $[&quot;OCRD&quot;.&quot;U_SS_Provincia&quot;] FROM DUMMY) INTO PROVINCIA FROM DUMMY; 
        '''SELECT DISTINCT left(&quot;U_SS_NomCan&quot;,65) FROM &quot;@SS_ESQCOD&quot; WHERE &quot;U_SS_NomPro&quot;= :PROVINCIA;.
        '''</summary>
        Friend ReadOnly Property SS_CANTON_HANA() As String
            Get
                Return ResourceManager.GetString("SS_CANTON_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @PROVINCIA VARCHAR(100)
        '''DECLARE @CANTON VARCHAR(100)
        '''SET @PROVINCIA = (SELECT $[$U_SS_Provincia.0.0])
        '''SELECT DISTINCT left(&quot;U_SS_NomCan&quot;,65) FROM &quot;@SS_ESQCOD&quot; WHERE &quot;U_SS_NomPro&quot;= @PROVINCIA.
        '''</summary>
        Friend ReadOnly Property SS_CANTON_SQL() As String
            Get
                Return ResourceManager.GetString("SS_CANTON_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1;Guayaquil
        '''2;Quito
        '''3;Cuenca
        '''4;Santo Domingo
        '''5;Machala
        '''6;Duran
        '''7;Manta
        '''8;Portoviejo
        '''9;Ambato
        '''10;Riobamba
        '''11;Quevedo
        '''12;Loja
        '''13;Ibarra
        '''14;Milagro
        '''15;Esmeraldas
        '''16;La Libertad
        '''17;Babahoyo
        '''18;Sangolqui
        '''19;Latacunga
        '''20;Tulcan
        '''21;Pasaje
        '''22;Chone
        '''23;Santa Rosa
        '''24;Huaquillas
        '''25;Nueva Loja
        '''26;El Carmen
        '''27;Jipijapa
        '''28;Ventanas
        '''29;Daule
        '''30;Cayambe
        '''31;Otavalo
        '''32;Velasco Ibarra
        '''33;Azogues
        '''34;Santa Elena
        '''35;Salinas
        '''36;La Troncal
        '''37;Buena Fe.
        '''</summary>
        Friend ReadOnly Property SS_CIUDADES() As String
            Get
                Return ResourceManager.GetString("SS_CIUDADES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &apos;PA&apos; AS Metodo, T0.&quot;DocEntry&quot;, T0.&quot;DocNum&quot;, SUBSTRING( T0.&quot;CardCode&quot;,0,19) AS CardCode, IFNULL(T0.&quot;CardName&quot;,&apos;&apos;) AS CardName, T0.&quot;DocDate&quot;,
        '''	CAST(T0.&quot;DocTotal&quot; AS DECIMAL (16,2)) AS DocTotal, (CASE WHEN T0.&quot;TrsfrSum&quot; &gt; 0 THEN &apos;CTA&apos; WHEN T0.&quot;CheckSum&quot; &gt; 0 THEN &apos;CHQ&apos; END) AS FormaPago, 
        '''	T0.&quot;DocCurr&quot; AS Moneda, (CASE WHEN T0.&quot;TrsfrSum&quot; &gt; 0 THEN &apos;CTE&apos; ELSE &apos;&apos; END) AS TipoCuenta, IFNULL(T1.&quot;DflAccount&quot;,&apos;&apos;) AS NumeroCuenta, 
        '''	T0.&quot;JrnlMemo&quot; AS Referencia, T1.&quot;U_TIPO_ID&quot; AS TipoCliente, T1.&quot;LicTradNum&quot; AS N [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_CM_CONSULTAPAGOEF_HANA() As String
            Get
                Return ResourceManager.GetString("SS_CM_CONSULTAPAGOEF_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &apos;PA&apos; AS Metodo, T0.DocEntry, T0.DocNum, SUBSTRING( T0.&quot;CardCode&quot;,0,19) AS CardCode, ISNULL(T0.CardName,&apos;&apos;) AS CardName, T0.DocDate,
        '''	CAST(T0.DocTotal AS DECIMAL (16,2)) AS DocTotal, (CASE WHEN T0.TrsfrSum &gt; 0 THEN &apos;CTA&apos; WHEN T0.CheckSum &gt; 0 THEN &apos;CHQ&apos; END) AS FormaPago , 
        '''	T0.DocCurr AS Moneda, (CASE WHEN T0.TrsfrSum &gt; 0 THEN &apos;CTE&apos; ELSE &apos;&apos; END) AS TipoCuenta, ISNULL(T1.DflAccount,&apos;&apos;) AS NumeroCuenta, 
        '''	T0.JrnlMemo AS Referencia, T1.U_TIPO_ID AS TipoCliente, T1.LicTradNum AS NumeroID, 
        '''	(CASE WHEN T1. [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_CM_CONSULTAPAGOEF_SQL() As String
            Get
                Return ResourceManager.GetString("SS_CM_CONSULTAPAGOEF_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &quot;U_CodBco&quot;, &quot;U_NomBco&quot;, &quot;U_CtaSys&quot;, &quot;U_NomCtaSys&quot;, &quot;U_CtaBco&quot; FROM &quot;@SS_CM_MBCOCTA&quot;.
        '''</summary>
        Friend ReadOnly Property SS_CM_CONSULTAPARAMETROSBC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_CM_CONSULTAPARAMETROSBC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT U_CodBco, U_NomBco, U_CtaSys, U_NomCtaSys, U_CtaBco FROM &quot;@SS_CM_MBCOCTA&quot; WITH(NOLOCK).
        '''</summary>
        Friend ReadOnly Property SS_CM_CONSULTAPARAMETROSBC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_CM_CONSULTAPARAMETROSBC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT A.&quot;U_Nombre&quot;, A.&quot;U_Valor&quot; FROM &quot;@SS_CONFD&quot; A INNER JOIN &quot;@SS_CONF&quot; B ON A.&quot;DocEntry&quot; = B.&quot;DocEntry&quot; WHERE B.&quot;U_Modulo&quot; = &apos;eLocalizacion&apos; AND B.&quot;U_Tipo&quot; = &apos;PARAMETROS&apos; AND B.&quot;U_Subtipo&quot; = &apos;CONFIGURACION&apos;.
        '''</summary>
        Friend ReadOnly Property SS_CM_CONSULTAPARAMETROSCONF_HANA() As String
            Get
                Return ResourceManager.GetString("SS_CM_CONSULTAPARAMETROSCONF_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT A.U_Nombre, A.U_Valor FROM &quot;@SS_CONFD&quot; A WITH(NOLOCK) INNER JOIN &quot;@SS_CONF&quot; B WITH(NOLOCK) ON A.DocEntry = B.DocEntry WHERE B.U_Modulo = &apos;eLocalizacion&apos; AND B.U_Tipo = &apos;PARAMETROS&apos; AND B.U_Subtipo = &apos;CONFIGURACION&apos;.
        '''</summary>
        Friend ReadOnly Property SS_CM_CONSULTAPARAMETROSCONF_SQL() As String
            Get
                Return ResourceManager.GetString("SS_CM_CONSULTAPARAMETROSCONF_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT T0.&quot;Code&quot; FROM OSTA T0 WHERE T0.&quot;Type&quot; =1.
        '''</summary>
        Friend ReadOnly Property SS_CODIGOS_FISCALES_IVA_HANA() As String
            Get
                Return ResourceManager.GetString("SS_CODIGOS_FISCALES_IVA_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT T0.[Code] FROM OSTA T0 WITH(NOLOCK) WHERE T0.Type =1.
        '''</summary>
        Friend ReadOnly Property SS_CODIGOS_FISCALES_IVA_SQL() As String
            Get
                Return ResourceManager.GetString("SS_CODIGOS_FISCALES_IVA_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 40;Exportación definitiva
        '''50;Exp temp para reimportacion 
        '''51;Exp temp para perfeccionamient
        '''60;Reexp.de mercancías 
        '''61;Reexp.de mercancías importadas
        '''79;Exp a consumo desde Zona franc
        '''83;Reembarque
        '''94;Courier exportación 
        '''95;Export Correos del Ecuador.
        '''</summary>
        Friend ReadOnly Property SS_CODIGOS_REGIMEN() As String
            Get
                Return ResourceManager.GetString("SS_CODIGOS_REGIMEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 019;Gquil-Aéreo
        '''028;Gquil-Marítimo
        '''037;Manta
        '''046;Esmeraldas
        '''055;Quito
        '''064;Pto-Bolívar
        '''073;Tulcán
        '''082;Huaquillas
        '''091;Cuenca
        '''109;Loja-Macara
        '''118;Sta Elena
        '''127;Latacunga
        '''136;Gerencia General
        '''145;CEBAF – San Miguel.
        '''</summary>
        Friend ReadOnly Property SS_DISTRITO_ADUANERO() As String
            Get
                Return ResourceManager.GetString("SS_DISTRITO_ADUANERO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OINV&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_Establec&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;FV&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_EST_FV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_EST_FV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OINV.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_Establec 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;FV&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_EST_FV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_EST_FV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;ODLN&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_Establec&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;GR&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_EST_GR_HANA() As String
            Get
                Return ResourceManager.GetString("SS_EST_GR_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[ODLN.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_Establec 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;GR&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_EST_GR_SQL() As String
            Get
                Return ResourceManager.GetString("SS_EST_GR_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OWTR&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_Establec&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;GRT&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_EST_GRT_HANA() As String
            Get
                Return ResourceManager.GetString("SS_EST_GRT_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OWTR.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_Establec 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;GRT&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_EST_GRT_SQL() As String
            Get
                Return ResourceManager.GetString("SS_EST_GRT_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OPCH&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_Establec&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; IN (&apos;LQ&apos;,&apos;RTLQ&apos;,&apos;RT&apos;)),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_EST_LQE_HANA() As String
            Get
                Return ResourceManager.GetString("SS_EST_LQE_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OPCH.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_Establec 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD IN (&apos;LQ&apos;,&apos;RTLQ&apos;,&apos;RT&apos;))
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_EST_LQE_SQL() As String
            Get
                Return ResourceManager.GetString("SS_EST_LQE_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;ORIN&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_Establec&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;NC&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_EST_NC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_EST_NC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[ORIN.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_Establec 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;NC&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_EST_NC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_EST_NC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OINV&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_Establec&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;ND&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_EST_ND_HANA() As String
            Get
                Return ResourceManager.GetString("SS_EST_ND_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OINV.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_Establec 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;ND&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_EST_ND_SQL() As String
            Get
                Return ResourceManager.GetString("SS_EST_ND_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE FECHA_CONTA VARCHAR(10);
        '''SELECT (select $[&quot;OPCH&quot;.&quot;DocDate&quot;] from dummy ) INTO FECHA_CONTA from dummy;
        '''SELECT FECHA_CONTA FROM DUMMY;.
        '''</summary>
        Friend ReadOnly Property SS_FECHA_RT_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FECHA_RT_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @FECHA_CONTA VARCHAR(10)
        '''SET @FECHA_CONTA = CONVERT(VARCHAR(10),(select $[opch.DOCDATE]),103)
        '''SELECT @FECHA_CONTA.
        '''</summary>
        Friend ReadOnly Property SS_FECHA_RT_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FECHA_RT_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare Sec integer;
        '''
        '''SELECT IFNULL( MAX(CAST(T0.&quot;Code&quot; AS INTEGER) )  , 0)+1
        '''into sec 
        '''FROM &quot;@SS_FPAGCOM&quot; T0 ;
        '''
        '''SELECT :sec 
        '''FROM DUMMY;.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_COMPRAS_SEC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_COMPRAS_SEC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @Sec as integer
        '''set @sec = iSnull((SELECT max(docentry) from [@SS_FPAGCOM]  T0 ) , 0) +1
        '''select @sec.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_COMPRAS_SEC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_COMPRAS_SEC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT MAX(CAST(T0.&quot;Code&quot; AS INTEGER) ) 
        '''FROM &quot;@SS_FPAGCOM&quot; T0 .
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_MAX_COMPRAS_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_MAX_COMPRAS_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT max(cast(CODE as int)) from [@SS_FPAGVEN].
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_MAX_COMRPAS_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_MAX_COMRPAS_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT MAX(CAST(T0.&quot;Code&quot; AS integer)  ) 
        '''FROM &quot;@SS_FPAGVEN&quot; T0.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_MAX_VENTAS_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_MAX_VENTAS_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @Sec as integer
        '''DECLARE @MAXNT INTEGER
        '''
        '''
        '''set @sec = iSnull((SELECT max(CODE) from [@SS_FPAGVEN]  T0 ) ) , 0) 
        '''select @sec.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_MAX_VENTAS_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_MAX_VENTAS_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE Sec integer;
        '''
        '''SELECT IFNULL( MAX(CAST(T0.&quot;Code&quot; AS INTEGER) )  , 0)+1
        '''into sec 
        '''FROM &quot;@SS_FPAGVEN&quot; T0 ;
        '''
        '''SELECT :sec 
        '''FROM DUMMY;.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_VENTA_SEC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_VENTA_SEC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @Sec as integer
        '''set @sec = iSnull((SELECT max(docentry) from [@SS_FPAGVEN]  T0 ) , 0) +1
        '''select @sec.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_VENTA_SEC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_VENTA_SEC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &quot;U_SS_FP_ID&quot; as Codigo, &quot;U_SS_FP_DESCRIPCION&quot; AS Descripcion
        '''FROM &quot;@SS_FORMAS_DE_PAGO&quot;
        '''order by 1.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_VENTAS_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_VENTAS_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT U_SS_FP_ID as Codigo, U_SS_FP_DESCRIPCION AS Descripcion
        '''FROM [@SS_FORMAS_DE_PAGO]
        '''order by 1.
        '''</summary>
        Friend ReadOnly Property SS_FORMAPAGO_VENTAS_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FORMAPAGO_VENTAS_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a select &quot;U_SS_FP_ID&quot; AS Codigo,&quot;U_SS_FP_DESCRIPCION&quot; as Descripcion from &quot;@SS_FORMAS_DE_PAGO&quot; order by 1.
        '''</summary>
        Friend ReadOnly Property SS_FORMASPAGO_HANA() As String
            Get
                Return ResourceManager.GetString("SS_FORMASPAGO_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a select U_SS_FP_ID AS Codigo,U_SS_FP_DESCRIPCION as Descripcion from &quot;@SS_FORMAS_DE_PAGO&quot; order by 1.
        '''</summary>
        Friend ReadOnly Property SS_FORMASPAGO_SQL() As String
            Get
                Return ResourceManager.GetString("SS_FORMASPAGO_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIES INTEGER;
        '''DECLARE DOCENTRY INTEGER;
        '''DECLARE DOCNUM INTEGER;
        '''DECLARE TARGETYPE INT;
        '''DECLARE BASEENTRY INT;
        '''DECLARE  DOCENTRYFAC VARCHAR(15);
        '''DECLARE CODIGO VARCHAR(100);
        '''
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocEntry&quot;] FROM dummy) INTO DOCENTRY FROM dummy;
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocNum&quot;] FROM dummy) INTO DOCNUM FROM dummy;
        '''SELECT (SELECT TOP 1 &quot;DocEntry&quot; from INV1 WHERE &quot;BaseEntry&quot;=:DOCENTRY and &quot;BaseRef&quot;=:DOCNUM )  INTO DOCENTRYFAC FROM dummy;
        '''SELECT TO_INT((SELECT TOP 1 &quot;TargetType&quot; from DLN1 WHERE &quot;Do [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_GR_ESTFAC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_GR_ESTFAC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(9)
        '''DECLARE @BASETYPE VARCHAR(49)
        '''
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @BASETYPE  = (select $[$-38.43])  
        '''
        '''IF @BASETYPE  = &apos;13&apos;
        '''BEGIN 
        '''SET @DESCRIPCION = (SELECT T0.U_SS_Est FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''END.
        '''</summary>
        Friend ReadOnly Property SS_GR_ESTFAC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_GR_ESTFAC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIES INTEGER;
        '''DECLARE DOCENTRY INTEGER;
        '''DECLARE DOCNUM INTEGER;
        '''DECLARE TARGETYPE INT;
        '''DECLARE BASEENTRY INT;
        '''DECLARE  DOCENTRYFAC VARCHAR(15);
        '''DECLARE CODIGO VARCHAR(100);
        '''
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocEntry&quot;] FROM dummy) INTO DOCENTRY FROM dummy;
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocNum&quot;] FROM dummy) INTO DOCNUM from dummy;
        '''SELECT (SELECT TOP 1 &quot;DocEntry&quot; from INV1 WHERE &quot;BaseEntry&quot;=:DOCENTRY and &quot;BaseRef&quot;=:DOCNUM )  INTO DOCENTRYFAC FROM dummy;
        '''SELECT TO_INT((SELECT TOP 1 &quot;TargetType&quot; from DLN1 WHERE &quot;Do [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_GR_FECHAFAC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_GR_FECHAFAC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION datetime
        '''DECLARE @BASETYPE VARCHAR(40)
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @BASETYPE  = (select $[$-38.43])  
        '''
        '''IF @BASETYPE  = &apos;13&apos;
        '''BEGIN 
        '''SET @DESCRIPCION = (SELECT T0.docdate FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''END
        '''SELECT @DESCRIPCION.
        '''</summary>
        Friend ReadOnly Property SS_GR_FECHAFAC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_GR_FECHAFAC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE COD_PROVEEDOR VARCHAR(30);
        '''DECLARE DIRECCION VARCHAR(30);
        '''DECLARE SERIES INTEGER;
        '''DECLARE DOCENTRY INTEGER;
        '''DECLARE DOCNUM INTEGER;
        '''DECLARE TARGETYPE INT;
        '''DECLARE BASEENTRY INT;
        '''DECLARE  DOCENTRYFAC VARCHAR(15);
        '''DECLARE SERIENAME VARCHAR(15);
        '''DECLARE CODIGO VARCHAR(100);
        '''
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocEntry&quot;] FROM dummy) INTO DOCENTRY FROM dummy;
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocNum&quot;] FROM dummy) INTO DOCNUM from dummy;
        '''SELECT (SELECT TOP 1 &quot;DocEntry&quot; from INV1 WHERE &quot;BaseEntry&quot;=:DOCENTRY and &quot;BaseRef&quot;=:DO [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_GR_FOLIOFAC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_GR_FOLIOFAC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(9)
        '''DECLARE @BASETYPE VARCHAR(40)
        '''
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @BASETYPE  = (select $[$-38.43])  
        '''
        '''IF @BASETYPE  = &apos;13&apos;
        '''BEGIN
        '''SET @DESCRIPCION = (SELECT T0.FOLIONUM FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''END
        '''SELECT @DESCRIPCION.
        '''</summary>
        Friend ReadOnly Property SS_GR_FOLIOFAC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_GR_FOLIOFAC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIES INTEGER;
        '''DECLARE DOCENTRY INTEGER;
        '''DECLARE DOCNUM INTEGER;
        '''DECLARE TARGETYPE INT;
        '''DECLARE BASEENTRY INT;
        '''DECLARE  DOCENTRYFAC VARCHAR(15);
        '''DECLARE CODIGO VARCHAR(100);
        '''
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocEntry&quot;] FROM dummy) INTO DOCENTRY FROM dummy;
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocNum&quot;] FROM dummy) INTO DOCNUM from dummy;
        '''SELECT (SELECT TOP 1 &quot;DocEntry&quot; from INV1 WHERE &quot;BaseEntry&quot;=:DOCENTRY and &quot;BaseRef&quot;=:DOCNUM)  INTO DOCENTRYFAC FROM dummy;
        '''SELECT TO_INT((SELECT TOP 1 &quot;TargetType&quot; from DLN1 WHERE &quot;Doc [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_GR_NUMAUTFAC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_GR_NUMAUTFAC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(49)
        '''DECLARE @BASETYPE VARCHAR(40)
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @BASETYPE  = (select $[$-38.43])  
        '''
        '''IF @BASETYPE  = &apos;13&apos;
        '''BEGIN
        '''SET @DESCRIPCION = (SELECT T0.U_SS_NumAut FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''END
        '''SELECT @DESCRIPCION.
        '''</summary>
        Friend ReadOnly Property SS_GR_NUMAUTOFC_REL_SQL() As String
            Get
                Return ResourceManager.GetString("SS_GR_NUMAUTOFC_REL_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIES INTEGER;
        '''DECLARE DOCENTRY INTEGER;
        '''DECLARE DOCNUM INTEGER;
        '''DECLARE TARGETYPE INT;
        '''DECLARE BASEENTRY INT;
        '''DECLARE  DOCENTRYFAC VARCHAR(15);
        '''DECLARE CODIGO VARCHAR(100);
        '''
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocEntry&quot;] FROM dummy) INTO DOCENTRY FROM dummy;
        '''SELECT (Select $[&quot;ODLN&quot;.&quot;DocNum&quot;] FROM dummy) INTO DOCNUM from dummy;
        '''SELECT (SELECT TOP 1 &quot;DocEntry&quot; from INV1 WHERE &quot;BaseEntry&quot;=:DOCENTRY and &quot;BaseRef&quot;=:DOCNUM)  INTO DOCENTRYFAC FROM dummy;
        '''SELECT TO_INT((SELECT TOP 1 &quot;TargetType&quot; from DLN1 WHERE &quot;Doc [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_GR_PTOEMIFAC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_GR_PTOEMIFAC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(9)
        '''DECLARE @BASETYPE VARCHAR(49)
        '''
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @BASETYPE  = (select $[$-38.43])  
        '''
        '''IF @BASETYPE  = &apos;13&apos;
        '''BEGIN 
        '''SET @DESCRIPCION = (SELECT T0.U_SS_Pemi FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''END
        '''
        '''SELECT @DESCRIPCION.
        '''</summary>
        Friend ReadOnly Property SS_GR_PUNTOEMISION_SQL() As String
            Get
                Return ResourceManager.GetString("SS_GR_PUNTOEMISION_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1;Enero
        '''2;Febrero
        '''3;Marzo
        '''4;Abril
        '''5;Mayo
        '''6;Junio
        '''7;Julio
        '''8;Agosto
        '''9;Septiembre
        '''10;Octubre
        '''11;Noviembre
        '''12;Diciembre.
        '''</summary>
        Friend ReadOnly Property SS_MES() As String
            Get
                Return ResourceManager.GetString("SS_MES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DT1;DEVOLUCION DE PRODUCTOS
        '''DT2;ANULACION DE FACTURA
        '''DT3;DESCUENTO EN VENTAS
        '''DT4;DEFECTOS DE FABRICA
        '''DT5;CAMBIO DE MARCADERIA
        '''DT6;RE FACTURACION
        '''DT7;OTROS
        '''DT8;CHEQUE PROTESTADO.
        '''</summary>
        Friend ReadOnly Property SS_MOTIVOS_NC() As String
            Get
                Return ResourceManager.GetString("SS_MOTIVOS_NC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE DOCENTRYFAC VARCHAR(9);
        '''DECLARE DESCRIPCION VARCHAR(9);
        '''DECLARE PRODUCTO VARCHAR(10);
        '''DECLARE OBJETYPE INT;
        '''
        '''select (select $[&quot;ORIN&quot;.&quot;DocType&quot;] from dummy) into PRODUCTO from dummy;
        '''
        '''IF :PRODUCTO = &apos;S&apos; THEN
        ''' SELECT ((select $[$-39.25.&quot;Number&quot;] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_INT((select $[$-39.23.&quot;BaseType&quot;] FROM DUMMY)) INTO OBJETYPE  FROM DUMMY;
        '''END IF;
        '''
        '''IF :PRODUCTO = &apos;I&apos; THEN
        ''' SELECT ((select $[$-38.45.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_INT((selec [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_EST_FAC_REL_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NC_EST_FAC_REL_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(10)
        '''DECLARE @DESCRIPCION VARCHAR(10)
        '''DECLARE @PRODUCTO VARCHAR(10)
        '''DECLARE @OBJETYPE INT
        '''SET @PRODUCTO = (SELECT $[ORIN.DOCTYPE])
        '''IF @PRODUCTO = &apos;S&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-39.25.Number]))
        '''SET @OBJETYPE = CONVERT(INT,(select $[$-39.23.BaseType]))
        '''END
        '''IF @PRODUCTO = &apos;I&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @OBJETYPE = CONVERT(INT,(select $[$-38.43.BaseType]))
        '''END
        '''
        '''IF @OBJETYPE = 13 
        '''BEGIN
        '''SET @DESCRIPCION = (SELECT T0.U_SS_Es [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_EST_FAC_REL_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NC_EST_FAC_REL_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE DOCENTRYFAC INTEGER;
        '''DECLARE DESCRIPCION TIMESTAMP;
        '''DECLARE PRODUCTO VARCHAR(10);
        '''DECLARE OBJETYPE INT;
        '''
        '''select (select $[&quot;ORIN&quot;.&quot;DocType&quot;] from dummy) into PRODUCTO from dummy;
        '''
        '''IF :PRODUCTO = &apos;S&apos; THEN
        ''' SELECT TO_INT((select $[$-39.25.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        '''SELECT TO_INT((select $[$-39.23.&quot;BaseType&quot;] FROM DUMMY)) INTO OBJETYPE  FROM DUMMY;
        '''END IF;
        '''
        '''IF :PRODUCTO = &apos;I&apos; THEN
        ''' SELECT TO_INT((select $[$-38.45.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_INT(( [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_FECHA_FC_REL_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NC_FECHA_FC_REL_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION datetime
        '''DECLARE @PRODUCTO VARCHAR(10)
        '''DECLARE @OBJETYPE INT
        '''SET @PRODUCTO = (SELECT $[ORIN.DOCTYPE])
        '''IF @PRODUCTO = &apos;S&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-39.25.Number]))
        '''SET @OBJETYPE = CONVERT(INT,(select $[$-39.23.BaseType]))
        '''END
        '''IF @PRODUCTO = &apos;I&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @OBJETYPE = CONVERT(INT,(select $[$-38.43.BaseType]))
        '''END 
        '''
        '''IF @OBJETYPE = 13 
        '''BEGIN
        '''SET @DESCRIPCION = (SELECT T0.docdate FR [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_FECHA_FC_REL_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NC_FECHA_FC_REL_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE DOCENTRYFAC VARCHAR(9);
        '''DECLARE DESCRIPCION VARCHAR(9);
        '''DECLARE PRODUCTO VARCHAR(10);
        '''DECLARE OBJETYPE INT;
        '''
        '''select (select $[&quot;ORIN&quot;.&quot;DocType&quot;] from dummy) into PRODUCTO from dummy;
        '''
        '''IF :PRODUCTO = &apos;S&apos; THEN
        ''' SELECT TO_INT((select $[$-39.25.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_INT((select $[$-39.23.&quot;BaseType&quot;] FROM DUMMY)) INTO OBJETYPE  FROM DUMMY;
        '''END IF;
        '''
        '''IF :PRODUCTO = &apos;I&apos; THEN
        ''' SELECT TO_INT((select $[$-38.45.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        '''SELECT TO_I [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_FOLIO_FC_REL_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NC_FOLIO_FC_REL_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(9)
        '''DECLARE @PRODUCTO VARCHAR(10)
        '''DECLARE @OBJETYPE INT
        '''SET @PRODUCTO = (SELECT $[ORIN.DOCTYPE])
        '''IF @PRODUCTO = &apos;S&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-39.25.Number]))
        '''SET @OBJETYPE = CONVERT(INT,(select $[$-39.23.BaseType]))
        '''END
        '''IF @PRODUCTO = &apos;I&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @OBJETYPE = CONVERT(INT,(select $[$-38.43.BaseType]))
        '''END 
        '''
        '''IF @OBJETYPE = 13 
        '''BEGIN
        '''SET @DESCRIPCION = (SELECT T0.FOLIONUM [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_FOLIO_FC_REL_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NC_FOLIO_FC_REL_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE DOCENTRYFAC VARCHAR(9);
        '''DECLARE DESCRIPCION VARCHAR(50);
        '''DECLARE PRODUCTO VARCHAR(10);
        '''DECLARE OBJETYPE INT;
        '''
        '''select (select $[&quot;ORIN&quot;.&quot;DocType&quot;] from dummy) into PRODUCTO from dummy;
        '''
        '''IF :PRODUCTO = &apos;S&apos; THEN
        ''' SELECT TO_INT((select $[$-39.25.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        '''SELECT TO_INT((select $[$-39.23.&quot;BaseType&quot;] FROM DUMMY)) INTO OBJETYPE  FROM DUMMY;
        '''END IF;
        '''
        '''IF :PRODUCTO = &apos;I&apos; THEN
        ''' SELECT TO_INT((select $[$-38.45.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_ [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_NUMAUTO_FAC_REL_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NC_NUMAUTO_FAC_REL_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(49)
        '''DECLARE @BASETYPE VARCHAR(40)
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''SET @BASETYPE  = (select $[$-38.43])  
        '''
        '''IF @BASETYPE  = &apos;13&apos;
        '''BEGIN
        '''SET @DESCRIPCION = (SELECT T0.U_SS_NumAut FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''END
        '''SELECT @DESCRIPCION.
        '''</summary>
        Friend ReadOnly Property SS_NC_NUMAUTO_FAC_REL_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NC_NUMAUTO_FAC_REL_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE DOCENTRYFAC VARCHAR(9);
        '''DECLARE DESCRIPCION VARCHAR(9);
        '''DECLARE PRODUCTO VARCHAR(10);
        '''DECLARE OBJETYPE INT;
        '''
        '''select (select $[&quot;ORIN&quot;.&quot;DocType&quot;] from dummy) into PRODUCTO from dummy;
        '''
        '''IF :PRODUCTO = &apos;S&apos; THEN
        ''' SELECT ((select $[$-39.25.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_INT((select $[$-39.23.&quot;BaseType&quot;] FROM DUMMY)) INTO OBJETYPE  FROM DUMMY;
        '''END IF;
        '''
        '''IF :PRODUCTO = &apos;I&apos; THEN
        ''' SELECT ((select $[$-38.45.Number] FROM dummy)) INTO DOCENTRYFAC  FROM dummy;
        ''' SELECT TO_INT((select  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NC_PUNTOEMISION_FC_REL_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NC_PUNTOEMISION_FC_REL_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT @DESCRIPCION.
        '''</summary>
        Friend ReadOnly Property SS_NC_PUNTOEMISION_FC_REL_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NC_PUNTOEMISION_FC_REL_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE serie2 varchar(10);
        '''DECLARE autorizacion varchar(49);
        '''
        '''SELECT (SELECT $[&quot;OINV&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''SELECT (SELECT T0.&quot;SeriesName&quot; FROM &quot;NNM1&quot; T0 WHERE TO_VARCHAR(t0.&quot;Series&quot;) = :serie) INTO serie2 FROM dummy ;
        '''
        '''SELECT (SELECT T0.&quot;U_NumAut&quot;  FROM &quot;@SS_DOCLEGALES&quot; T0
        '''where T0.&quot;U_Documento&quot; = :serie2 AND T0.&quot;U_Estado&quot; = &apos;A&apos; AND T0.&quot;U_TipoDoc&quot; = &apos;FV&apos;)  INTO autorizacion FROM dummy ;
        '''
        '''SELECT autorizacion FROM dummy ;.
        '''</summary>
        Friend ReadOnly Property SS_NUM_AUTO_FV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NUM_AUTO_FV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''declare @serie2 varchar(10)
        '''declare @autorizacion varchar(49)
        '''
        '''set @serie = (Select $[oinv.series])
        '''
        '''set @serie2 = (SELECT T0.SERIESNAME
        '''  FROM [NNM1] T0 WITH(NOLOCK)
        '''  WHERE t0.series = @serie)
        '''
        '''SET @autorizacion= (SELECT T0.[U_NumAut] FROM [dbo].[@SS_DOCLEGALES]  T0 WITH(NOLOCK)
        '''where t0.u_Documento = @serie2 AND T0.U_ESTADO = &apos;A&apos; AND T0.U_TIPODOC = &apos;FV&apos;)
        '''
        '''select @autorizacion.
        '''</summary>
        Friend ReadOnly Property SS_NUM_AUTO_FV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUM_AUTO_FV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''declare @serie2 varchar(10)
        '''declare @autorizacion varchar(49)
        '''
        '''set @serie = (Select $[OPCH.series])
        '''
        '''set @serie2 = (SELECT T0.SERIESNAME
        '''  FROM [NNM1] T0 WITH(NOLOCK)
        '''  WHERE t0.series = @serie)
        '''
        '''SET @autorizacion= (SELECT T0.[U_NumAut] FROM [dbo].[@SS_DOCLEGALES]  T0 WITH(NOLOCK)
        '''where t0.u_Documento = @serie2 AND T0.U_ESTADO = &apos;A&apos; AND T0.U_TIPODOC = &apos;RT&apos;)
        '''
        '''select @autorizacion.
        '''</summary>
        Friend ReadOnly Property SS_NUM_AUTO_RT_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUM_AUTO_RT_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE DESCRIPCION VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''select (select $[&quot;ODLN&quot;.&quot;Series&quot;] from dummy) into SERIE from dummy;
        '''
        '''select (SELECT T1.&quot;SeriesName&quot; FROM &quot;NNM1&quot; T1 WHERE TO_VARCHAR(T1.&quot;Series&quot;) = (select SERIE from dummy)) into DESCRIPCION from dummy;
        '''
        '''select (SELECT TOP 1 IFNULL(T2.&quot;U_NumAut&quot;, &apos;&apos;) FROM &quot;@SS_DOCLEGALES&quot; T2 WHERE T2.&quot;U_Documento&quot; = (select DESCRIPCION from dummy) AND  t2.&quot;U_Estado&quot; = &apos;A&apos; AND T2.&quot;U_TipoDoc&quot; = &apos;GR&apos;) into CODIGO from dummy;
        '''select CODI [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_GR_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_GR_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @DESCRIPCION VARCHAR(100)
        '''DECLARE @CODIGO VARCHAR(37)
        '''
        '''
        '''SET @SERIE = (select $[ODLN.series])
        '''SET @DESCRIPCION = (SELECT T1.SERIESNAME FROM NNM1 T1 WHERE T1.SERIES = @SERIE )
        '''
        '''SET @CODIGO = (SELECT TOP 1 ISNULL(U_NumAut,&apos;&apos;) 
        '''		FROM [dbo].[@SS_DOCLEGALES]  T2 
        '''		WHERE T2.U_Documento = @DESCRIPCION AND  t2.u_Estado = &apos;A&apos; AND T2.U_TipoDoc = &apos;GR&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_GR_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_GR_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE NUMAUTOR VARCHAR(49);
        '''DECLARE DIRECCION VARCHAR(30);
        '''DECLARE SERIES INTEGER;
        '''DECLARE SERIENAME VARCHAR(15);
        '''DECLARE CODIGO VARCHAR(49);
        '''
        '''SELECT (Select $[&quot;OPCH&quot;.&quot;U_NUM_AUTOR&quot;] FROM dummy) INTO NUMAUTOR FROM dummy;
        '''SELECT (Select $[&quot;OPCH&quot;.&quot;Series&quot;] FROM dummy) INTO SERIES FROM dummy;
        '''SELECT (SELECT T0.&quot;SeriesName&quot; FROM &quot;NNM1&quot; T0 WHERE T0.&quot;ObjectCode&quot; = &apos;18&apos; AND T0.&quot;Series&quot; = :SERIES) INTO SERIENAME FROM dummy;  
        '''
        '''IF :SERIENAME LIKE &apos;LQE%&apos; THEN
        '''SELECT &apos;0000000000&apos; INTO CODIGO  FROM dummy;
        '''SELECT CODIG [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_LQE_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_LQE_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @COD_PROVEEDOR VARCHAR(30)
        '''DECLARE @DIRECCION VARCHAR(30)
        '''DECLARE @SERIES INT
        '''DECLARE @SERIENAME VARCHAR(15)
        '''DECLARE @CODIGO VARCHAR(3)
        '''SET @SERIES = (Select $[opch.series])
        '''SET @SERIENAME  = (SELECT SERIESNAME FROM NNM1 WITH(NOLOCK) WHERE ObjectCode = 18 AND Series = @SERIES )
        '''SET @COD_PROVEEDOR = (Select $[opch.cardcode])
        '''SET @DIRECCION = (Select $[opch.paytocode])
        '''
        '''IF @SERIENAME LIKE &apos;LQE%&apos;
        '''BEGIN 
        '''SET @CODIGO = &apos;0000000000&apos;
        ''' SELECT @CODIGO
        '''END
        '''else
        '''begin
        '''SET @CODIGO = &apos;&apos;
        ''' SELECT @CODIGO
        '''end.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_LQE_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_LQE_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE SERIE2 VARCHAR(100);
        '''DECLARE AUTORIZACION VARCHAR(49);
        '''
        '''select (select $[&quot;ORIN&quot;.&quot;series&quot;] from dummy) into SERIE from dummy;
        '''select (SELECT T1.&quot;SeriesName&quot; FROM &quot;NNM1&quot; T1 WHERE TO_VARCHAR(T1.&quot;Series&quot;) = (select SERIE from dummy)) into SERIE2 from dummy;
        '''
        '''select (SELECT T0.&quot;U_NumAut&quot; FROM &quot;@SS_DOCLEGALES&quot; T0 WHERE T0.&quot;U_Documento&quot; = (select SERIE2 from dummy) 
        '''AND  T0.&quot;U_Estado&quot; = &apos;A&apos; AND T0.&quot;U_TipoDoc&quot; = &apos;NC&apos;) into AUTORIZACION from dummy;
        '''select AUTORIZACION from dummy;.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_NC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_NC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INTEGER
        '''DECLARE @DESCRIPCION VARCHAR(100)
        '''DECLARE @CODIGO VARCHAR(49)
        '''SET @SERIE = (select $[ORIn.series])
        '''SET @DESCRIPCION = (SELECT top 1 T1.SERIESNAME FROM NNM1 T1 WITH(NOLOCK) WHERE T1.SERIES = @SERIE)
        '''SET @CODIGO = (SELECT top 1 ISNULL(T2.U_NumAut,&apos;&apos;) FROM [dbo].[@SS_DOCLEGALES]  T2 WITH(NOLOCK) WHERE T2.U_Documento = @DESCRIPCION AND T2.u_Estado  = &apos;A&apos; AND T2.U_TipoDoc = &apos;NC&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_NC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_NC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE INTEGER;
        '''DECLARE SERIE2 VARCHAR(6);
        '''DECLARE AUTORIZACION VARCHAR(37);
        '''
        '''select (select $[&quot;OINV&quot;.&quot;series&quot;] from dummy) into SERIE from dummy;
        '''select (SELECT T1.&quot;SeriesName&quot; FROM &quot;NNM1&quot; T1 WHERE T1.&quot;Series&quot; = :SERIE ) into SERIE2 from dummy;
        '''
        '''select (SELECT T0.&quot;U_NumAut&quot; FROM &quot;@SS_DOCLEGALES&quot; T0 WHERE T0.&quot;U_Documento&quot; = :SERIE2 AND  T0.&quot;U_Estado&quot; = &apos;A&apos; AND T0.&quot;U_TipoDoc&quot; = &apos;ND&apos;) into AUTORIZACION from dummy;
        '''select AUTORIZACION from dummy;.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_ND_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_ND_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''declare @serie2 varchar(10)
        '''declare @autorizacion varchar(49)
        '''
        '''set @serie = (Select $[oinv.series])
        '''
        '''set @serie2 = (SELECT T0.SERIESNAME
        '''  FROM [NNM1] T0 WITH(NOLOCK)
        '''  WHERE t0.series = @serie)
        '''
        '''SET @autorizacion= (SELECT T0.[U_NumAut] FROM [dbo].[@SS_DOCLEGALES]  T0 WITH(NOLOCK)
        '''where t0.u_Documento = @serie2 AND T0.U_ESTADO = &apos;A&apos; AND T0.U_TIPODOC = &apos;ND&apos;)
        '''
        '''select @autorizacion.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_ND_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_ND_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE INTEGER;
        '''DECLARE SERIE2 VARCHAR(6);
        '''DECLARE AUTORIZACION VARCHAR(37);
        '''
        '''select (select $[&quot;OINV&quot;.&quot;series&quot;] from dummy) into SERIE from dummy;
        '''select (SELECT T1.&quot;SeriesName&quot; FROM &quot;NNM1&quot; T1 WHERE T1.&quot;Series&quot; = :SERIE ) into SERIE2 from dummy;
        '''
        '''select (SELECT T0.&quot;U_NumAut&quot; FROM &quot;@SS_DOCLEGALES&quot; T0 WHERE T0.&quot;U_Documento&quot; = :SERIE2 AND  T0.&quot;U_Estado&quot; = &apos;A&apos; AND T0.&quot;U_TipoDoc&quot; = &apos;RT&apos;) into AUTORIZACION from dummy;
        '''select AUTORIZACION from dummy;.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_RT_HANA() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_RT_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INTEGER
        '''DECLARE @DESCRIPCION VARCHAR(100)
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''
        '''SET @SERIE = (select $[OPCH.series])
        '''SET @DESCRIPCION = (SELECT T1.SERIESNAME FROM NNM1 T1 WHERE T1.SERIES = @SERIE )
        '''
        '''SET @CODIGO = (SELECT T2.U_NumAut FROM [dbo].[@SS_DOCLEGALES]  T2 WHERE T2.U_Documento = @DESCRIPCION AND  t2.u_estado = &apos;A&apos; AND T2.U_TIPODOC = &apos;RT&apos;)
        '''
        '''   SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_NUMAUTO_RT_SQL() As String
            Get
                Return ResourceManager.GetString("SS_NUMAUTO_RT_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 101;ARGENTINA                     
        '''102;BOLIVIA                       
        '''103;BRASIL                        
        '''104;CANADA                        
        '''105;COLOMBIA                      
        '''106;COSTA RICA                    
        '''107;CUBA                          
        '''108;CHILE                         
        '''109;ANGUILA                       
        '''110;ESTADOS UNIDOS                
        '''111;GUATEMALA                     
        '''112;HAITI                         
        '''113;HONDURAS                      
        '''114;JAMAICA                       
        '''115;MALVINAS ISLAS     [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_PAISES() As String
            Get
                Return ResourceManager.GetString("SS_PAISES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE PROVINCIA VARCHAR(100);
        '''DECLARE CANTON VARCHAR(100);
        '''SELECT (SELECT $[&quot;OCRD&quot;.&quot;U_SS_Provincia&quot;] FROM DUMMY) INTO PROVINCIA FROM DUMMY; 
        '''SELECT (SELECT $[&quot;OCRD&quot;.&quot;U_SS_Canton&quot;] FROM DUMMY) INTO CANTON FROM DUMMY; 
        '''SELECT DISTINCT left(&quot;U_SS_NomPar&quot;,65) FROM &quot;@SS_ESQCOD&quot; WHERE &quot;U_SS_NomPro&quot;= :PROVINCIA AND &quot;U_SS_NomCan&quot;= :CANTON;.
        '''</summary>
        Friend ReadOnly Property SS_PARROQUIA_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PARROQUIA_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @PROVINCIA VARCHAR(100)
        '''DECLARE @CANTON VARCHAR(100)
        '''SET @PROVINCIA = (SELECT $[$U_SS_Provincia.0.0])
        '''SET @CANTON = (SELECT $[$U_SS_Canton.0.0])
        '''SELECT DISTINCT left(&quot;U_SS_NomPar&quot;,65) FROM &quot;@SS_ESQCOD&quot; WHERE &quot;U_SS_NomPro&quot;= @PROVINCIA AND &quot;U_SS_NomCan&quot;= @CANTON.
        '''</summary>
        Friend ReadOnly Property SS_PARROQUIA_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PARROQUIA_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &apos;N&apos; AS chek, T0.&quot;DocEntry&quot;, T0.&quot;DocNum&quot;, T0.&quot;U_Tipo&quot;, T0.&quot;U_MedioPago&quot;, T0.&quot;Creator&quot;, T0.&quot;CreateDate&quot;, (SELECT SUM(T1.&quot;U_Pago&quot;) FROM &quot;@SS_PM_DET1&quot; T1 WHERE T0.&quot;DocEntry&quot; = T1.&quot;DocEntry&quot;) AS Pagar FROM &quot;@SS_PM_CAB&quot; T0.
        '''</summary>
        Friend ReadOnly Property SS_PM_OBTENERPAGOS_UDO_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PM_OBTENERPAGOS_UDO_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT &apos;N&apos; AS chek, T0.DocEntry, T0.DocNum, T0.&quot;U_Tipo&quot;, T0.&quot;U_MedioPago&quot;, T0.Creator, T0.CreateDate, (SELECT SUM(T1.U_Pago) FROM &quot;@SS_PM_DET1&quot; T1 WHERE T0.DocEntry = T1.DocEntry) AS Pagar FROM &quot;@SS_PM_CAB&quot; T0.
        '''</summary>
        Friend ReadOnly Property SS_PM_OBTENERPAGOS_UDO_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PM_OBTENERPAGOS_UDO_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 01;01;50;AZUAY;CUENCA;CUENCA
        '''01;01;51;AZUAY;CUENCA;BAÑOS
        '''01;01;52;AZUAY;CUENCA;CUMBE
        '''01;01;53;AZUAY;CUENCA;CHAUCHA
        '''01;01;54;AZUAY;CUENCA;CHECA (JIDCAY)
        '''01;01;55;AZUAY;CUENCA;CHIQUINTAD
        '''01;01;56;AZUAY;CUENCA;LLACAO
        '''01;01;57;AZUAY;CUENCA;MOLLETURO
        '''01;01;58;AZUAY;CUENCA;NULTI
        '''01;01;59;AZUAY;CUENCA;OCTAVIO CORDERO PALACIOS (SANTA ROSA)
        '''01;01;60;AZUAY;CUENCA;PACCHA
        '''01;01;61;AZUAY;CUENCA;QUINGEO
        '''01;01;62;AZUAY;CUENCA;RICAURTE
        '''01;01;63;AZUAY;CUENCA;SAN JOAQUIN
        '''01;01;64;AZUAY;CUENCA;SANTA ANA
        '''01;01;65;AZUAY;CUENCA; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_PROVINCIA_CANTON_PARROQUIA() As String
            Get
                Return ResourceManager.GetString("SS_PROVINCIA_CANTON_PARROQUIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 001;Azuay
        '''002;Bolívar
        '''003;Cañar
        '''004;Carchi
        '''005;Chimborazo
        '''006;Cotopaxi
        '''007;El Oro
        '''008;Esmeraldas
        '''009;Galápagos
        '''010;Guayas
        '''011;Imbabura
        '''012;Loja
        '''013;Los Ríos
        '''014;Manabí
        '''015;Morona-Santiago
        '''016;Napo
        '''017;Orellana
        '''018;Pastaza
        '''019;Pichincha
        '''020;Santa Elena
        '''021;Santo Domingo de los Tsáchilas
        '''022;Sucumbíos
        '''023;Tungurahua
        '''024;Zamora-Chinchipe.
        '''</summary>
        Friend ReadOnly Property SS_PROVINCIAS() As String
            Get
                Return ResourceManager.GetString("SS_PROVINCIAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select * from (SELECT DISTINCT left(&quot;U_SS_NomPro&quot;,65) AS &quot;Provincia&quot; from &quot;@SS_ESQCOD&quot; ) X0 ORDER BY X0.&quot;Provincia&quot;.
        '''</summary>
        Friend ReadOnly Property SS_PROVINCIAS_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PROVINCIAS_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT DISTINCT left(&quot;U_SS_NomPro&quot;,65) from &quot;@SS_ESQCOD&quot; ORDER BY &quot;U_SS_NomPro&quot;.
        '''</summary>
        Friend ReadOnly Property SS_PROVINCIAS_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PROVINCIAS_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OINV&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_PuntoEmi&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;FV&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_FV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_FV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OINV.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_PuntoEmi 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;FV&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_FV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_FV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;ODLN&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_PuntoEmi&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;GR&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_GR_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_GR_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[ODLN.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_PuntoEmi 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;GR&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_GR_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_GR_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OWTR&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_PuntoEmi&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; = &apos;GRT&apos;),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_GRT_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_GRT_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OWTR.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_PuntoEmi 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD = &apos;GRT&apos;)
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_GRT_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_GRT_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OPCH&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_PuntoEmi&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; IN (&apos;LQ&apos;,&apos;RTLQ&apos;,&apos;RT&apos;)),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_LQE_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_LQE_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OPCH.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_PuntoEmi 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD  IN (&apos;LQ&apos;,&apos;RTLQ&apos;,&apos;RT&apos;))
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_LQE_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_LQE_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;ORIN&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_PuntoEmi&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; IN (&apos;NC&apos;)),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_NC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_NC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[ORIN.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_PuntoEmi 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD  IN (&apos;NC&apos;))
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_NC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_NC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OINV&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT T2.&quot;U_PuntoEmi&quot; FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; IN (&apos;ND&apos;)),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_ND_HANA() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_ND_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OINV.series])
        '''
        '''SET @CODIGO = (SELECT T2.U_PuntoEmi 
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD  IN (&apos;ND&apos;))
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_PUNTOEMISION_ND_SQL() As String
            Get
                Return ResourceManager.GetString("SS_PUNTOEMISION_ND_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT t0.&quot;U_SS_SerEst&quot; FROM CRD1 T0 WHERE T0.&quot;CardCode&quot; = (select  $[$13_U_E.0.0] from dummy).
        '''</summary>
        Friend ReadOnly Property SS_REEM_ESTBPROV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_REEM_ESTBPROV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT t0.U_SS_SerEst FROM CRD1 T0 WHERE T0.[CardCode] =  $[$13_U_E.0.0].
        '''</summary>
        Friend ReadOnly Property SS_REEM_ESTBPROV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_REEM_ESTBPROV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT T0.&quot;CardCode&quot; as Codigo, T0.&quot;CardName&quot; as Descripcion
        '''FROM &quot;OCRD&quot; T0
        '''WHERE T0.&quot;CardType&quot; = &apos;S&apos;
        '''ORDER BY T0.&quot;CardCode&quot;.
        '''</summary>
        Friend ReadOnly Property SS_REEM_PROV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_REEM_PROV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT CardCode as Codigo, CardName as Descripcion
        '''FROM OCRD T0
        '''WHERE T0.CardType = &apos;S&apos;
        '''ORDER BY CardCode.
        '''</summary>
        Friend ReadOnly Property SS_REEM_PROV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_REEM_PROV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT SUBSTRING(t1.&quot;SS_PtoEmi&quot;,1,3) FROM CRD1 T1  WHERE T1.&quot;CardCode&quot; = (select  $[$13_U_E.0.0] from dummy).
        '''</summary>
        Friend ReadOnly Property SS_REEM_PTOPROV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_REEM_PTOPROV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT SUBSTRING(t1.SS_PtoEmi,1,3) FROM CRD1 T1 WHERE T1.[CardCode] =  $[$13_U_E.0.0].
        '''</summary>
        Friend ReadOnly Property SS_REEM_PTOPROV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_REEM_PTOPROV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT max(cast(&quot;Code&quot; as int)) from &quot;@SS_REEMCAB&quot;.
        '''</summary>
        Friend ReadOnly Property SS_REEMBOLSO_MAX_HANA() As String
            Get
                Return ResourceManager.GetString("SS_REEMBOLSO_MAX_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT max(cast(CODE as int)) from [@SS_REEMCAB].
        '''</summary>
        Friend ReadOnly Property SS_REEMBOLSO_MAX_SQL() As String
            Get
                Return ResourceManager.GetString("SS_REEMBOLSO_MAX_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare v_Sec INTEGER;
        '''select (ifnull((SELECT max(t0.&quot;Code&quot;) from &quot;@SS_REEMCAB&quot; T0),0)+1) into v_Sec from dummy ; 
        '''SELECT v_Sec from dummy ;.
        '''</summary>
        Friend ReadOnly Property SS_REEMBOLSO_SEC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_REEMBOLSO_SEC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @Sec as integer
        '''set @sec = iSnull((SELECT max(Code) from [@SS_REEMCAB] T0 ) , 0) +1
        '''select @sec.
        '''</summary>
        Friend ReadOnly Property SS_REEMBOLSO_SEC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_REEMBOLSO_SEC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a select &quot;Code&quot; AS &quot;Codigo&quot;, &quot;Name&quot; as &quot;Descripcion&quot; from &quot;@SS_TIPOIDENT&quot;.
        '''</summary>
        Friend ReadOnly Property SS_REEMBOLSO_TIPOID_HANA() As String
            Get
                Return ResourceManager.GetString("SS_REEMBOLSO_TIPOID_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a select Code AS Codigo, NAME as Descripcion from [@SS_TIPOIDENT].
        '''</summary>
        Friend ReadOnly Property SS_REEMBOLSO_TIPOID_SQL() As String
            Get
                Return ResourceManager.GetString("SS_REEMBOLSO_TIPOID_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SERIE VARCHAR(100);
        '''DECLARE CODIGO VARCHAR(15);
        '''
        '''SELECT (SELECT $[&quot;OPCH&quot;.&quot;Series&quot;] FROM dummy) INTO SERIE FROM dummy;
        '''
        '''SELECT IFNULL((SELECT IFNULL(T2.&quot;U_Establec&quot;,&apos;&apos;) || IFNULL(T2.&quot;U_PuntoEmi&quot;,&apos;&apos;) FROM &quot;@SS_SERD&quot; T2 
        '''WHERE T2.&quot;U_SerId&quot; = :SERIE  AND T2.&quot;U_TipoD&quot; IN (&apos;RT&apos;)),&apos;000&apos;)
        '''INTO CODIGO FROM dummy;
        '''
        '''SELECT CODIGO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_SERIE_RETENCION_HANA() As String
            Get
                Return ResourceManager.GetString("SS_SERIE_RETENCION_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @SERIE INT
        '''DECLARE @CODIGO VARCHAR(15)
        '''
        '''SET @SERIE = (select $[OPCH.series])
        '''
        '''SET @CODIGO = (SELECT ISNULL(T2.&quot;U_Establec&quot;,&apos;&apos;) + ISNULL(T2.&quot;U_PuntoEmi&quot;,&apos;&apos;)
        '''		FROM [dbo].[@SS_SERD]  T2 
        '''		WHERE T2.U_SerId = @SERIE AND  T2.U_TipoD IN (&apos;RT&apos;))
        '''
        '''SELECT @CODIGO.
        '''</summary>
        Friend ReadOnly Property SS_SERIE_RETENCION_SQL() As String
            Get
                Return ResourceManager.GetString("SS_SERIE_RETENCION_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --;NINGUNO
        '''00;NO APLICA
        '''01;CRED TRIBUTARIO P DECLARAC IVA
        '''02;COSTO O GTO P DECLARAC DE IR
        '''03;ACT. FIJO -CRED TRIB P DEC IVA
        '''04;AFIJO COSTO O GTO P DECLARA I
        '''05;LIQ.GTO VIAJ, HOSP,ALIM,GTO IR
        '''06;INV.CRED TRIB P DEC DE IVA
        '''07;INV.COSTO O GASTOS P DEC DE IR
        '''08;VALOR PAG. P SOL REMBOLS GTO
        '''09;REMBOLSO PARA SINIESTRO
        '''10;DISTRIBUCIÓN DE DIVIDENDOS, BENEFICIOS Y UTILIDADES
        '''11;CONVENIO DE DÉBITO O RECAUDACIÓN PARA IFIS
        '''12;IMPUESTOS Y RETENCIONES PRESUNTIVOS
        '''13;VALORES RECONOCIDOS POR ENTIDADES DEL SECTOR PÚBLICO A  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_SUSTENTOTRIBUTARIO() As String
            Get
                Return ResourceManager.GetString("SS_SUSTENTOTRIBUTARIO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE SUSTENTO VARCHAR(2);
        '''
        '''SELECT (SELECT T0.&quot;Code&quot; FROM &quot;@SS_SUSTRI&quot; T0  WHERE T0.&quot;Code&quot; = &apos;--&apos;) INTO SUSTENTO  FROM dummy;
        '''
        '''SELECT SUSTENTO FROM dummy;.
        '''</summary>
        Friend ReadOnly Property SS_SUSTRI_HANA() As String
            Get
                Return ResourceManager.GetString("SS_SUSTRI_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT left(T0.&quot;Code&quot;,2) as &quot;CÓDIGO&quot; ,T0.&quot;Name&quot;  AS &quot;DESCRIPCIÓN&quot;  FROM &quot;@SS_TIPCOMAUT&quot; T0
        '''WHERE  T0.&quot;Code&quot; IN (&apos;01_1&apos;,&apos;18&apos;,&apos;41_1&apos;) 
        '''ORDER BY T0.&quot;Name&quot;.
        '''</summary>
        Friend ReadOnly Property SS_TIPO_COMPROBANTE_FV_HANA() As String
            Get
                Return ResourceManager.GetString("SS_TIPO_COMPROBANTE_FV_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT LEFT(CODE,2) AS CÓDIGO,Name AS DESCRIPCIÓN  FROM [dbo].[@SS_TIPCOMAUT]  
        '''WHERE CODE IN (&apos;01_1&apos;,&apos;18&apos;,&apos;41_1&apos;)
        '''ORDER BY Name.
        '''</summary>
        Friend ReadOnly Property SS_TIPO_COMPROBANTE_FV_SQL() As String
            Get
                Return ResourceManager.GetString("SS_TIPO_COMPROBANTE_FV_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT left(T0.&quot;Code&quot;,2) AS &quot;CÓDIGO&quot;,T0.&quot;Name&quot; AS &quot;DESCRIPCIÓN&quot;  FROM &quot;@SS_TIPCOMAUT&quot; T0
        '''WHERE  T0.&quot;Code&quot; IN (&apos;04_1&apos;,&apos;47_1&apos;).
        '''</summary>
        Friend ReadOnly Property SS_TIPO_COMPROBANTE_NC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_TIPO_COMPROBANTE_NC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT LEFT(CODE,2) AS CÓDIGO,Name AS DESCRIPCIÓN  FROM [dbo].[@SS_TIPCOMAUT]  
        '''WHERE CODE IN (&apos;04_1&apos;,&apos;47_1&apos;).
        '''</summary>
        Friend ReadOnly Property SS_TIPO_COMPROBANTE_NC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_TIPO_COMPROBANTE_NC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT SUBSTRING(T0.&quot;Code&quot;,1,2) AS &quot;Code&quot;, T0.&quot;Name&quot; FROM &quot;@SS_TIPCOMAUT&quot;  T0.
        '''</summary>
        Friend ReadOnly Property SS_TIPO_COMPROBANTES_SRI_COMPRAS_HANA() As String
            Get
                Return ResourceManager.GetString("SS_TIPO_COMPROBANTES_SRI_COMPRAS_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT SUBSTRING(T0.CODE,1,2), T0.[NAME] 
        ''' FROM [dbo].[@SS_TIPCOMAUT]  T0
        ''' WHERE T0.[U_SS_TipoTra] = 1.
        '''</summary>
        Friend ReadOnly Property SS_TIPO_COMPROBANTES_SRI_COMPRAS_SQL() As String
            Get
                Return ResourceManager.GetString("SS_TIPO_COMPROBANTES_SRI_COMPRAS_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE DOCENTRYFAC VARCHAR(9);
        '''DECLARE DESCRIPCION VARCHAR(2);
        '''DECLARE PRODUCTO VARCHAR(10);
        '''DECLARE OBJETYPE INT;
        '''
        '''select (SELECT $[&quot;ORIN&quot;.&quot;DocType&quot;] from dummy) into PRODUCTO from Dummy ;
        '''IF PRODUCTO = &apos;S&apos;
        '''THEN
        '''  SELECT (SELECT ($[$-39.25.&quot;Number&quot;]) FROM DUMMY ) INTO  DOCENTRYFAC FROM DUMMY;
        '''  SELECT TO_INT((select $[$-39.23.&quot;BaseType&quot;] FROM DUMMY)) INTO OBJETYPE  FROM DUMMY;
        '''END IF; 
        '''IF PRODUCTO = &apos;I&apos;
        '''THEN
        '''  SELECT (SELECT ($[$-38.45.&quot;Number&quot;]) FROM DUMMY ) INTO  DOCENTRYFAC FROM DUMMY;
        '''  SELECT TO_INT( [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_TIPOCOMPROBANTE_APLICA_NC_HANA() As String
            Get
                Return ResourceManager.GetString("SS_TIPOCOMPROBANTE_APLICA_NC_HANA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @DOCENTRYFAC VARCHAR(9)
        '''DECLARE @DESCRIPCION VARCHAR(2)
        '''DECLARE @PRODUCTO VARCHAR(1)
        '''SET @PRODUCTO = (SELECT $[ORIN.DOCTYPE])
        '''IF @PRODUCTO = &apos;S&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-39.25.Number]))
        '''END
        '''IF @PRODUCTO = &apos;I&apos;
        '''BEGIN
        '''SET @DOCENTRYFAC =CONVERT(INT,(select $[$-38.45.Number]))
        '''END
        '''SET @DESCRIPCION = (SELECT T0.U_SS_TipCom FROM OINV T0 WITH(NOLOCK) WHERE T0.DOCENTRY = @DOCENTRYFAC)
        '''
        '''
        '''
        '''IF ISNULL(@DESCRIPCION,&apos;&apos;)=&apos;&apos;
        '''BEGIN
        '''SELECT LEFT(CODE,2) AS CÓDIGO,Name AS DESCRIPCIÓN FROM [dbo].[@ [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_TIPOCOMPROBANTE_APLICA_NC_SQL() As String
            Get
                Return ResourceManager.GetString("SS_TIPOCOMPROBANTE_APLICA_NC_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 01;FACTURA;A;1
        '''01_1;FACTURA EXPORTAC;A;2;2
        '''02;NOTA O BOLETA DE VENTAS;A;1
        '''03;LIQUID.COMPRAS;A;1
        '''04;NOTA DE CREDITO;A;1
        '''04_1;NOTA DE CREDITO VTAS;A;2
        '''04_2;NOTA DE CREDITO EXPORTAC;A;4
        '''05;NOTA DE DEBITO;A;1
        '''05_1;NOTA DEBITO VENTAS;A;2
        '''05_2;NOTA DEBITO EXPORTACION;A;4
        '''06;GUÍA DE REMISIÓN;A;2
        '''07;COMPROBANTE DE RETENCION;A;
        '''08;BOLETOS O ENTRADAS A ESPECTAC.;A;1
        '''09;TICK O VALES EMITIDOS X MAQ. R;A;1
        '''11;PASAJES EXP X EMP DE AVIACION;A;1
        '''12;DOCUMENTOS EMITID X INST FIN.;A;1
        '''15;COMPROB. VTA.EMITID EN EL EXT.;A;1
        '''16; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_TIPOS_COMPROBANTES() As String
            Get
                Return ResourceManager.GetString("SS_TIPOS_COMPROBANTES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 401;Rentas Inmobiliarias 
        '''402;Beneficios  y servicios Empresariales  / Asistencia técnica
        '''403;Beneficios  y servicios Empresariales  / Comisiones 
        '''404;Beneficios  y servicios Empresariales / Comisiones sobre préstamos
        '''405;Beneficios  y servicios Empresariales/Honorarios
        '''406;Beneficios  y servicios Empresariales / Publicidad 
        '''407;Beneficios  y servicios Empresariales / Servicios administrativos
        '''408;Beneficios  y servicios Empresariales / Servicios financieros
        '''409;Beneficios  y servicios Empresariales /Servic [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SS_TIPOS_INGRESOS_EXTERIOR() As String
            Get
                Return ResourceManager.GetString("SS_TIPOS_INGRESOS_EXTERIOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a C;CEDULA
        '''F;CONSUMIDOR FINAL
        '''P;PASAPORTE
        '''R;RUC.
        '''</summary>
        Friend ReadOnly Property SS_TIPOSIDENTIFICACION() As String
            Get
                Return ResourceManager.GetString("SS_TIPOSIDENTIFICACION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 1;Compras
        '''2;Ventas
        '''4;Exportación
        '''5;Tarjetas de Crédito
        '''6;Rendimientos Financieros
        '''7;Fondos Financieros.
        '''</summary>
        Friend ReadOnly Property SS_TIPOTRANSACCION() As String
            Get
                Return ResourceManager.GetString("SS_TIPOTRANSACCION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
