'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsEDoc_GuiaRemision
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IWSEDOCNUBE_GUIAS_REMISION", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSEDOCNUBE_GUIAS_REMISION
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarGuiaRemisionSRIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Entidades.My.MySettings.Default.Entidades_wsEDoc_GuiaRemision_WSEDOC_GUIAS_REMISION
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarGuiaRemisionSRICompleted As EnviarGuiaRemisionSRICompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSEDOCNUBE_GUIAS_REMISION/EnviarGuiaRemisionSRI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarGuiaRemisionSRI(ByVal Credencial As String, ByVal Entorno As String, ByVal GuiaRemision As ENTGuiaRemision, ByRef mensaje As String) As RespuestaEDOC
            Dim results() As Object = Me.Invoke("EnviarGuiaRemisionSRI", New Object() {Credencial, Entorno, GuiaRemision, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),RespuestaEDOC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarGuiaRemisionSRIAsync(ByVal Credencial As String, ByVal Entorno As String, ByVal GuiaRemision As ENTGuiaRemision, ByVal mensaje As String)
            Me.EnviarGuiaRemisionSRIAsync(Credencial, Entorno, GuiaRemision, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarGuiaRemisionSRIAsync(ByVal Credencial As String, ByVal Entorno As String, ByVal GuiaRemision As ENTGuiaRemision, ByVal mensaje As String, ByVal userState As Object)
            If (Me.EnviarGuiaRemisionSRIOperationCompleted Is Nothing) Then
                Me.EnviarGuiaRemisionSRIOperationCompleted = AddressOf Me.OnEnviarGuiaRemisionSRIOperationCompleted
            End If
            Me.InvokeAsync("EnviarGuiaRemisionSRI", New Object() {Credencial, Entorno, GuiaRemision, mensaje}, Me.EnviarGuiaRemisionSRIOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarGuiaRemisionSRIOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarGuiaRemisionSRICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarGuiaRemisionSRICompleted(Me, New EnviarGuiaRemisionSRICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTGuiaRemision
        
        Private campo1Field As String
        
        Private campo2Field As String
        
        Private campo3Field As String
        
        Private campo4Field As String
        
        Private campo5Field As String
        
        Private campo6Field As String
        
        Private campo7Field As String
        
        Private campo8Field As String
        
        Private campo9Field As String
        
        Private campo10Field As String
        
        Private codigoTransaccionERPField As String
        
        Private usuarioProcesoField As String
        
        Private usuarioTransaccionERPField As String
        
        Private rucTranportistaField As String
        
        Private idGuiaRemisionField As Long
        
        Private autorizacionSRIField As String
        
        Private fechaAutorizacionField As System.Nullable(Of Date)
        
        Private ambienteField As Integer
        
        Private tipoEmisionField As Integer
        
        Private razonSocialField As String
        
        Private nombreComercialField As String
        
        Private rucField As String
        
        Private claveAccesoField As String
        
        Private codigoDocumentoField As String
        
        Private establecimientoField As String
        
        Private puntoEmisionField As String
        
        Private secuencialField As String
        
        Private direccionMatrizField As String
        
        Private direccionEstablecimientoField As String
        
        Private direccionPartidaField As String
        
        Private razonSocialTransportistaField As String
        
        Private tipoIdentificacionTransportistaField As String
        
        Private riseField As String
        
        Private obligadoContabilidadField As String
        
        Private contribuyenteEspecialField As String
        
        Private fechaInicioTransporteField As Date
        
        Private fechaFinTransporteField As Date
        
        Private fechaEmisionField As Date
        
        Private placaField As String
        
        Private estadoField As Integer
        
        Private secuencialERPField As String
        
        Private eNTGuiaRemisionDestinatarioField() As ENTGuiaRemisionDestinatario
        
        Private emailResponsableField As String
        
        Private eNTDatoAdicionalGuiaRemisionField() As ENTDatoAdicionalGuiaRemision
        
        Private eNTDatosOpcionalesField As ENTDatosOpcionales
        
        Private datosFacturadorManualField As DatosFacturadorManual
        
        '''<remarks/>
        Public Property Campo1() As String
            Get
                Return Me.campo1Field
            End Get
            Set
                Me.campo1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo2() As String
            Get
                Return Me.campo2Field
            End Get
            Set
                Me.campo2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo3() As String
            Get
                Return Me.campo3Field
            End Get
            Set
                Me.campo3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo4() As String
            Get
                Return Me.campo4Field
            End Get
            Set
                Me.campo4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo5() As String
            Get
                Return Me.campo5Field
            End Get
            Set
                Me.campo5Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo6() As String
            Get
                Return Me.campo6Field
            End Get
            Set
                Me.campo6Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo7() As String
            Get
                Return Me.campo7Field
            End Get
            Set
                Me.campo7Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo8() As String
            Get
                Return Me.campo8Field
            End Get
            Set
                Me.campo8Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo9() As String
            Get
                Return Me.campo9Field
            End Get
            Set
                Me.campo9Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo10() As String
            Get
                Return Me.campo10Field
            End Get
            Set
                Me.campo10Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoTransaccionERP() As String
            Get
                Return Me.codigoTransaccionERPField
            End Get
            Set
                Me.codigoTransaccionERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioProceso() As String
            Get
                Return Me.usuarioProcesoField
            End Get
            Set
                Me.usuarioProcesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioTransaccionERP() As String
            Get
                Return Me.usuarioTransaccionERPField
            End Get
            Set
                Me.usuarioTransaccionERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RucTranportista() As String
            Get
                Return Me.rucTranportistaField
            End Get
            Set
                Me.rucTranportistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdGuiaRemision() As Long
            Get
                Return Me.idGuiaRemisionField
            End Get
            Set
                Me.idGuiaRemisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AutorizacionSRI() As String
            Get
                Return Me.autorizacionSRIField
            End Get
            Set
                Me.autorizacionSRIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaAutorizacion() As System.Nullable(Of Date)
            Get
                Return Me.fechaAutorizacionField
            End Get
            Set
                Me.fechaAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ambiente() As Integer
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoEmision() As Integer
            Get
                Return Me.tipoEmisionField
            End Get
            Set
                Me.tipoEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreComercial() As String
            Get
                Return Me.nombreComercialField
            End Get
            Set
                Me.nombreComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ruc() As String
            Get
                Return Me.rucField
            End Get
            Set
                Me.rucField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoDocumento() As String
            Get
                Return Me.codigoDocumentoField
            End Get
            Set
                Me.codigoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Establecimiento() As String
            Get
                Return Me.establecimientoField
            End Get
            Set
                Me.establecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PuntoEmision() As String
            Get
                Return Me.puntoEmisionField
            End Get
            Set
                Me.puntoEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Secuencial() As String
            Get
                Return Me.secuencialField
            End Get
            Set
                Me.secuencialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionMatriz() As String
            Get
                Return Me.direccionMatrizField
            End Get
            Set
                Me.direccionMatrizField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionEstablecimiento() As String
            Get
                Return Me.direccionEstablecimientoField
            End Get
            Set
                Me.direccionEstablecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionPartida() As String
            Get
                Return Me.direccionPartidaField
            End Get
            Set
                Me.direccionPartidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocialTransportista() As String
            Get
                Return Me.razonSocialTransportistaField
            End Get
            Set
                Me.razonSocialTransportistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificacionTransportista() As String
            Get
                Return Me.tipoIdentificacionTransportistaField
            End Get
            Set
                Me.tipoIdentificacionTransportistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Rise() As String
            Get
                Return Me.riseField
            End Get
            Set
                Me.riseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObligadoContabilidad() As String
            Get
                Return Me.obligadoContabilidadField
            End Get
            Set
                Me.obligadoContabilidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContribuyenteEspecial() As String
            Get
                Return Me.contribuyenteEspecialField
            End Get
            Set
                Me.contribuyenteEspecialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaInicioTransporte() As Date
            Get
                Return Me.fechaInicioTransporteField
            End Get
            Set
                Me.fechaInicioTransporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaFinTransporte() As Date
            Get
                Return Me.fechaFinTransporteField
            End Get
            Set
                Me.fechaFinTransporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEmision() As Date
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                Me.fechaEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As Integer
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecuencialERP() As String
            Get
                Return Me.secuencialERPField
            End Get
            Set
                Me.secuencialERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTGuiaRemisionDestinatario() As ENTGuiaRemisionDestinatario()
            Get
                Return Me.eNTGuiaRemisionDestinatarioField
            End Get
            Set
                Me.eNTGuiaRemisionDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailResponsable() As String
            Get
                Return Me.emailResponsableField
            End Get
            Set
                Me.emailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatoAdicionalGuiaRemision() As ENTDatoAdicionalGuiaRemision()
            Get
                Return Me.eNTDatoAdicionalGuiaRemisionField
            End Get
            Set
                Me.eNTDatoAdicionalGuiaRemisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatosOpcionales() As ENTDatosOpcionales
            Get
                Return Me.eNTDatosOpcionalesField
            End Get
            Set
                Me.eNTDatosOpcionalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatosFacturadorManual() As DatosFacturadorManual
            Get
                Return Me.datosFacturadorManualField
            End Get
            Set
                Me.datosFacturadorManualField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTGuiaRemisionDestinatario
        
        Private idGuiaRemisionDestinatarioField As Long
        
        Private identificacionDestinatarioField As String
        
        Private razonSocialDestinatarioField As String
        
        Private dirDestinatarioField As String
        
        Private motivoTrasladoField As String
        
        Private docAduaneroUnicoField As String
        
        Private codEstabDestinoField As String
        
        Private rutaField As String
        
        Private codDocSustentoField As String
        
        Private numDocSustentoField As String
        
        Private numAutDocSustentoField As String
        
        Private fechaEmisionDocSustentoField As Date
        
        Private idGuiaRemisionField As Long
        
        Private eNTGuiaRemisionDetalleField() As ENTGuiaRemisionDetalle
        
        '''<remarks/>
        Public Property IdGuiaRemisionDestinatario() As Long
            Get
                Return Me.idGuiaRemisionDestinatarioField
            End Get
            Set
                Me.idGuiaRemisionDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionDestinatario() As String
            Get
                Return Me.identificacionDestinatarioField
            End Get
            Set
                Me.identificacionDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocialDestinatario() As String
            Get
                Return Me.razonSocialDestinatarioField
            End Get
            Set
                Me.razonSocialDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirDestinatario() As String
            Get
                Return Me.dirDestinatarioField
            End Get
            Set
                Me.dirDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MotivoTraslado() As String
            Get
                Return Me.motivoTrasladoField
            End Get
            Set
                Me.motivoTrasladoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocAduaneroUnico() As String
            Get
                Return Me.docAduaneroUnicoField
            End Get
            Set
                Me.docAduaneroUnicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstabDestino() As String
            Get
                Return Me.codEstabDestinoField
            End Get
            Set
                Me.codEstabDestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ruta() As String
            Get
                Return Me.rutaField
            End Get
            Set
                Me.rutaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodDocSustento() As String
            Get
                Return Me.codDocSustentoField
            End Get
            Set
                Me.codDocSustentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumDocSustento() As String
            Get
                Return Me.numDocSustentoField
            End Get
            Set
                Me.numDocSustentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumAutDocSustento() As String
            Get
                Return Me.numAutDocSustentoField
            End Get
            Set
                Me.numAutDocSustentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEmisionDocSustento() As Date
            Get
                Return Me.fechaEmisionDocSustentoField
            End Get
            Set
                Me.fechaEmisionDocSustentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdGuiaRemision() As Long
            Get
                Return Me.idGuiaRemisionField
            End Get
            Set
                Me.idGuiaRemisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTGuiaRemisionDetalle() As ENTGuiaRemisionDetalle()
            Get
                Return Me.eNTGuiaRemisionDetalleField
            End Get
            Set
                Me.eNTGuiaRemisionDetalleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTGuiaRemisionDetalle
        
        Private idGuiaRemisionDetalleField As Long
        
        Private codigoInternoField As String
        
        Private codigoAdicionalField As String
        
        Private descripcionField As String
        
        Private cantidadField As Decimal
        
        Private idGuiaRemisionDestinatarioField As Long
        
        Private eNTDatoAdicionalGuiaRemisionDetalleField() As ENTDatoAdicionalGuiaRemisionDetalle
        
        '''<remarks/>
        Public Property IdGuiaRemisionDetalle() As Long
            Get
                Return Me.idGuiaRemisionDetalleField
            End Get
            Set
                Me.idGuiaRemisionDetalleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoInterno() As String
            Get
                Return Me.codigoInternoField
            End Get
            Set
                Me.codigoInternoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoAdicional() As String
            Get
                Return Me.codigoAdicionalField
            End Get
            Set
                Me.codigoAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdGuiaRemisionDestinatario() As Long
            Get
                Return Me.idGuiaRemisionDestinatarioField
            End Get
            Set
                Me.idGuiaRemisionDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatoAdicionalGuiaRemisionDetalle() As ENTDatoAdicionalGuiaRemisionDetalle()
            Get
                Return Me.eNTDatoAdicionalGuiaRemisionDetalleField
            End Get
            Set
                Me.eNTDatoAdicionalGuiaRemisionDetalleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatoAdicionalGuiaRemisionDetalle
        
        Private idDatoAdicionalGuiaRemisionDetalleField As Long
        
        Private nombreField As String
        
        Private descripcionField As String
        
        Private idGuiaRemisionDetalleField As Long
        
        '''<remarks/>
        Public Property IdDatoAdicionalGuiaRemisionDetalle() As Long
            Get
                Return Me.idDatoAdicionalGuiaRemisionDetalleField
            End Get
            Set
                Me.idDatoAdicionalGuiaRemisionDetalleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdGuiaRemisionDetalle() As Long
            Get
                Return Me.idGuiaRemisionDetalleField
            End Get
            Set
                Me.idGuiaRemisionDetalleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EComprobante
        
        Private claveAccesoField As String
        
        Private mensajesField() As EMensaje
        
        '''<remarks/>
        Public Property claveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensajes() As EMensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EMensaje
        
        Private identificadorField As String
        
        Private mensaje1Field As String
        
        Private informacionAdicionalField As String
        
        Private tipoField As String
        
        '''<remarks/>
        Public Property identificador() As String
            Get
                Return Me.identificadorField
            End Get
            Set
                Me.identificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje1() As String
            Get
                Return Me.mensaje1Field
            End Get
            Set
                Me.mensaje1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property informacionAdicional() As String
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                Me.informacionAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EAutorizacion
        
        Private estadoField As String
        
        Private numeroAutorizacionField As String
        
        Private claveAccesoField As String
        
        Private fechaAutorizacionField As Date
        
        Private fechaAutorizacionFieldSpecified As Boolean
        
        Private fechaAutorizacionSpecified1Field As Boolean
        
        Private ambienteField As String
        
        Private comprobanteField As String
        
        Private mensajesField() As EMensaje
        
        '''<remarks/>
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroAutorizacion() As String
            Get
                Return Me.numeroAutorizacionField
            End Get
            Set
                Me.numeroAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fechaAutorizacion() As Date
            Get
                Return Me.fechaAutorizacionField
            End Get
            Set
                Me.fechaAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaAutorizacionSpecified() As Boolean
            Get
                Return Me.fechaAutorizacionFieldSpecified
            End Get
            Set
                Me.fechaAutorizacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("fechaAutorizacionSpecified")>  _
        Public Property fechaAutorizacionSpecified1() As Boolean
            Get
                Return Me.fechaAutorizacionSpecified1Field
            End Get
            Set
                Me.fechaAutorizacionSpecified1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ambiente() As String
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comprobante() As String
            Get
                Return Me.comprobanteField
            End Get
            Set
                Me.comprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensajes() As EMensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaEDOC
        
        Private claveAccesoField As String
        
        Private numeroComprobantesField As String
        
        Private estadoField As String
        
        Private autorizacionesField() As EAutorizacion
        
        Private comprobantesField() As EComprobante
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroComprobantes() As String
            Get
                Return Me.numeroComprobantesField
            End Get
            Set
                Me.numeroComprobantesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property autorizaciones() As EAutorizacion()
            Get
                Return Me.autorizacionesField
            End Get
            Set
                Me.autorizacionesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comprobantes() As EComprobante()
            Get
                Return Me.comprobantesField
            End Get
            Set
                Me.comprobantesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DatosFacturadorManual
        
        Private facturadorManualField As Boolean
        
        Private usaDirectorioField As Integer
        
        '''<remarks/>
        Public Property FacturadorManual() As Boolean
            Get
                Return Me.facturadorManualField
            End Get
            Set
                Me.facturadorManualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaDirectorio() As Integer
            Get
                Return Me.usaDirectorioField
            End Get
            Set
                Me.usaDirectorioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatosOpcionales
        
        Private mailResponsableField As String
        
        Private usuarioCreadorField As String
        
        Private directorioDocumentoField As String
        
        Private nombreDocumentoField As String
        
        '''<remarks/>
        Public Property MailResponsable() As String
            Get
                Return Me.mailResponsableField
            End Get
            Set
                Me.mailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioCreador() As String
            Get
                Return Me.usuarioCreadorField
            End Get
            Set
                Me.usuarioCreadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirectorioDocumento() As String
            Get
                Return Me.directorioDocumentoField
            End Get
            Set
                Me.directorioDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreDocumento() As String
            Get
                Return Me.nombreDocumentoField
            End Get
            Set
                Me.nombreDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatoAdicionalGuiaRemision
        
        Private idDatoAdicionalGuiaRemisionField As Long
        
        Private nombreField As String
        
        Private descripcionField As String
        
        Private idGuiaRemisionField As Long
        
        '''<remarks/>
        Public Property IdDatoAdicionalGuiaRemision() As Long
            Get
                Return Me.idDatoAdicionalGuiaRemisionField
            End Get
            Set
                Me.idDatoAdicionalGuiaRemisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdGuiaRemision() As Long
            Get
                Return Me.idGuiaRemisionField
            End Get
            Set
                Me.idGuiaRemisionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub EnviarGuiaRemisionSRICompletedEventHandler(ByVal sender As Object, ByVal e As EnviarGuiaRemisionSRICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarGuiaRemisionSRICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEDOC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEDOC)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
