'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsEDoc_ConsultaRecepcionArchivo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IWSRAD_KEY_ARCHIVO", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSRAD_KEY_ARCHIVO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultaArchivoProveedor_PDFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaArchivoProveedor_PDF_URLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CargarClavesAccesoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Entidades.My.MySettings.Default.Entidades_wsEDoc_ConsultaRecepcionArchivo_WSRAD_KEY_ARCHIVO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultaArchivoProveedor_PDFCompleted As ConsultaArchivoProveedor_PDFCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaArchivoProveedor_PDF_URLCompleted As ConsultaArchivoProveedor_PDF_URLCompletedEventHandler
        
        '''<remarks/>
        Public Event CargarClavesAccesoCompleted As CargarClavesAccesoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSRAD_KEY_ARCHIVO/ConsultaArchivoProveedor_PDF", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaArchivoProveedor_PDF(ByVal CiaTipoAlojamientoKey As String, ByVal TipoDocumento As Integer, ByVal IdDocumento As Long, ByRef mensaje As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("ConsultaArchivoProveedor_PDF", New Object() {CiaTipoAlojamientoKey, TipoDocumento, IdDocumento, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaArchivoProveedor_PDFAsync(ByVal CiaTipoAlojamientoKey As String, ByVal TipoDocumento As Integer, ByVal IdDocumento As Long, ByVal mensaje As String)
            Me.ConsultaArchivoProveedor_PDFAsync(CiaTipoAlojamientoKey, TipoDocumento, IdDocumento, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaArchivoProveedor_PDFAsync(ByVal CiaTipoAlojamientoKey As String, ByVal TipoDocumento As Integer, ByVal IdDocumento As Long, ByVal mensaje As String, ByVal userState As Object)
            If (Me.ConsultaArchivoProveedor_PDFOperationCompleted Is Nothing) Then
                Me.ConsultaArchivoProveedor_PDFOperationCompleted = AddressOf Me.OnConsultaArchivoProveedor_PDFOperationCompleted
            End If
            Me.InvokeAsync("ConsultaArchivoProveedor_PDF", New Object() {CiaTipoAlojamientoKey, TipoDocumento, IdDocumento, mensaje}, Me.ConsultaArchivoProveedor_PDFOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaArchivoProveedor_PDFOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaArchivoProveedor_PDFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaArchivoProveedor_PDFCompleted(Me, New ConsultaArchivoProveedor_PDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSRAD_KEY_ARCHIVO/ConsultaArchivoProveedor_PDF_URL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaArchivoProveedor_PDF_URL(ByVal CiaTipoAlojamientoKey As String, ByVal TipoDocumento As Integer, ByVal IdDocumento As Long, ByRef mensaje As String) As String
            Dim results() As Object = Me.Invoke("ConsultaArchivoProveedor_PDF_URL", New Object() {CiaTipoAlojamientoKey, TipoDocumento, IdDocumento, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaArchivoProveedor_PDF_URLAsync(ByVal CiaTipoAlojamientoKey As String, ByVal TipoDocumento As Integer, ByVal IdDocumento As Long, ByVal mensaje As String)
            Me.ConsultaArchivoProveedor_PDF_URLAsync(CiaTipoAlojamientoKey, TipoDocumento, IdDocumento, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaArchivoProveedor_PDF_URLAsync(ByVal CiaTipoAlojamientoKey As String, ByVal TipoDocumento As Integer, ByVal IdDocumento As Long, ByVal mensaje As String, ByVal userState As Object)
            If (Me.ConsultaArchivoProveedor_PDF_URLOperationCompleted Is Nothing) Then
                Me.ConsultaArchivoProveedor_PDF_URLOperationCompleted = AddressOf Me.OnConsultaArchivoProveedor_PDF_URLOperationCompleted
            End If
            Me.InvokeAsync("ConsultaArchivoProveedor_PDF_URL", New Object() {CiaTipoAlojamientoKey, TipoDocumento, IdDocumento, mensaje}, Me.ConsultaArchivoProveedor_PDF_URLOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaArchivoProveedor_PDF_URLOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaArchivoProveedor_PDF_URLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaArchivoProveedor_PDF_URLCompleted(Me, New ConsultaArchivoProveedor_PDF_URLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSRAD_KEY_ARCHIVO/CargarClavesAcceso", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CargarClavesAcceso(ByVal CiaTipoAlojamientoKey As String, ByVal ListaClaveAcceso() As String, ByRef mensaje As String) As Boolean
            Dim results() As Object = Me.Invoke("CargarClavesAcceso", New Object() {CiaTipoAlojamientoKey, ListaClaveAcceso, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CargarClavesAccesoAsync(ByVal CiaTipoAlojamientoKey As String, ByVal ListaClaveAcceso() As String, ByVal mensaje As String)
            Me.CargarClavesAccesoAsync(CiaTipoAlojamientoKey, ListaClaveAcceso, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CargarClavesAccesoAsync(ByVal CiaTipoAlojamientoKey As String, ByVal ListaClaveAcceso() As String, ByVal mensaje As String, ByVal userState As Object)
            If (Me.CargarClavesAccesoOperationCompleted Is Nothing) Then
                Me.CargarClavesAccesoOperationCompleted = AddressOf Me.OnCargarClavesAccesoOperationCompleted
            End If
            Me.InvokeAsync("CargarClavesAcceso", New Object() {CiaTipoAlojamientoKey, ListaClaveAcceso, mensaje}, Me.CargarClavesAccesoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCargarClavesAccesoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CargarClavesAccesoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CargarClavesAccesoCompleted(Me, New CargarClavesAccesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ConsultaArchivoProveedor_PDFCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaArchivoProveedor_PDFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaArchivoProveedor_PDFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ConsultaArchivoProveedor_PDF_URLCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaArchivoProveedor_PDF_URLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaArchivoProveedor_PDF_URLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub CargarClavesAccesoCompletedEventHandler(ByVal sender As Object, ByVal e As CargarClavesAccesoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CargarClavesAccesoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
