'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSEDOCNUBE_FACTURAS_v4_3
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IWSEDOCNUBE_FACTURAS", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSEDOCNUBE_FACTURAS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarFacturaSRIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarFacturaSRI_XMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Entidades.My.MySettings.Default.Entidades_WSEDOCNUBE_FACTURAS_v4_3_WSEDOCNUBE_FACTURAS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarFacturaSRICompleted As EnviarFacturaSRICompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarFacturaSRI_XMLCompleted As EnviarFacturaSRI_XMLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSEDOCNUBE_FACTURAS/EnviarFacturaSRI", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarFacturaSRI(ByVal Credencial As String, ByVal Entorno As String, ByVal Factura As ENTFactura, ByRef mensaje As String) As RespuestaEDOC
            Dim results() As Object = Me.Invoke("EnviarFacturaSRI", New Object() {Credencial, Entorno, Factura, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),RespuestaEDOC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarFacturaSRIAsync(ByVal Credencial As String, ByVal Entorno As String, ByVal Factura As ENTFactura, ByVal mensaje As String)
            Me.EnviarFacturaSRIAsync(Credencial, Entorno, Factura, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarFacturaSRIAsync(ByVal Credencial As String, ByVal Entorno As String, ByVal Factura As ENTFactura, ByVal mensaje As String, ByVal userState As Object)
            If (Me.EnviarFacturaSRIOperationCompleted Is Nothing) Then
                Me.EnviarFacturaSRIOperationCompleted = AddressOf Me.OnEnviarFacturaSRIOperationCompleted
            End If
            Me.InvokeAsync("EnviarFacturaSRI", New Object() {Credencial, Entorno, Factura, mensaje}, Me.EnviarFacturaSRIOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarFacturaSRIOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarFacturaSRICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarFacturaSRICompleted(Me, New EnviarFacturaSRICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSEDOCNUBE_FACTURAS/EnviarFacturaSRI_XML", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarFacturaSRI_XML(ByVal clave As String, ByVal Entorno As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal Factura() As Byte, ByRef mensaje As String) As RespuestaEDOC
            Dim results() As Object = Me.Invoke("EnviarFacturaSRI_XML", New Object() {clave, Entorno, Factura, mensaje})
            mensaje = CType(results(1),String)
            Return CType(results(0),RespuestaEDOC)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarFacturaSRI_XMLAsync(ByVal clave As String, ByVal Entorno As String, ByVal Factura() As Byte, ByVal mensaje As String)
            Me.EnviarFacturaSRI_XMLAsync(clave, Entorno, Factura, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarFacturaSRI_XMLAsync(ByVal clave As String, ByVal Entorno As String, ByVal Factura() As Byte, ByVal mensaje As String, ByVal userState As Object)
            If (Me.EnviarFacturaSRI_XMLOperationCompleted Is Nothing) Then
                Me.EnviarFacturaSRI_XMLOperationCompleted = AddressOf Me.OnEnviarFacturaSRI_XMLOperationCompleted
            End If
            Me.InvokeAsync("EnviarFacturaSRI_XML", New Object() {clave, Entorno, Factura, mensaje}, Me.EnviarFacturaSRI_XMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarFacturaSRI_XMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarFacturaSRI_XMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarFacturaSRI_XMLCompleted(Me, New EnviarFacturaSRI_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFactura
        
        Private tipoField As System.Nullable(Of Integer)
        
        Private eNTFacturaCompensacionField() As ENTCompensacion
        
        Private eNTFacturaPagosField() As ENTFacturaPagos
        
        Private eNTFacturaReembolsoField() As ENTFacturaReembolso
        
        Private comercioExteriorField As String
        
        Private incoTermFacturaField As String
        
        Private lugarIncoTermField As String
        
        Private paisOrigenField As String
        
        Private puertoEmbarqueField As String
        
        Private puertoDestinoField As String
        
        Private paisDestinoField As String
        
        Private paisAdquisicionField As String
        
        Private dirCompradorField As String
        
        Private incoTermTotalSinImpuestosField As String
        
        Private fleteInternacionalField As System.Nullable(Of Decimal)
        
        Private seguroInternacionalField As System.Nullable(Of Decimal)
        
        Private gastosAduanerosField As System.Nullable(Of Decimal)
        
        Private gastosTransporteOtrosField As System.Nullable(Of Decimal)
        
        Private campo1Field As String
        
        Private campo2Field As String
        
        Private campo3Field As String
        
        Private campo4Field As String
        
        Private campo5Field As String
        
        Private campo6Field As String
        
        Private campo7Field As String
        
        Private campo8Field As String
        
        Private campo9Field As String
        
        Private campo10Field As String
        
        Private campo11Field As String
        
        Private campo12Field As String
        
        Private campo13Field As String
        
        Private campo14Field As String
        
        Private campo15Field As String
        
        Private codigoTransaccionERPField As String
        
        Private usuarioProcesoField As String
        
        Private usuarioTransaccionERPField As String
        
        Private idFacturaField As Long
        
        Private autorizacionSRIField As String
        
        Private fechaAutorizacionField As System.Nullable(Of Date)
        
        Private ambienteField As Integer
        
        Private tipoEmisionField As Integer
        
        Private razonSocialField As String
        
        Private nombreComercialField As String
        
        Private rucField As String
        
        Private claveAccesoField As String
        
        Private codigoDocumentoField As String
        
        Private establecimientoField As String
        
        Private puntoEmisionField As String
        
        Private secuencialField As String
        
        Private direccionMatrizField As String
        
        Private fechaEmisionField As Date
        
        Private direccionEstablecimientoField As String
        
        Private contribuyenteEspecialField As String
        
        Private obligadoContabilidadField As String
        
        Private tipoIdentificacionCompradorField As String
        
        Private guiaRemisionField As String
        
        Private razonSocialCompradorField As String
        
        Private identificacionCompradorField As String
        
        Private totalSinImpuestoField As Decimal
        
        Private totalSubsidioField As System.Nullable(Of Decimal)
        
        Private totalDescuentoField As Decimal
        
        Private codDocReembField As String
        
        Private totalComprobantesReembolsoField As System.Nullable(Of Decimal)
        
        Private totalBaseImponibleReembolsoField As System.Nullable(Of Decimal)
        
        Private totalImpuestoReembolsoField As System.Nullable(Of Decimal)
        
        Private propinaField As Decimal
        
        Private importeTotalField As Decimal
        
        Private monedaField As String
        
        Private valorRetIvaField As System.Nullable(Of Decimal)
        
        Private valorRetRentaField As System.Nullable(Of Decimal)
        
        Private estadoField As Integer
        
        Private secuencialERPField As String
        
        Private eNTFacturaImpuestoField() As ENTFacturaImpuesto
        
        Private eNTDatoAdicionalFacturaField() As ENTDatoAdicionalFactura
        
        Private emailResponsableField As String
        
        Private fechaCargaField As String
        
        Private eNTDetalleFacturaField() As ENTDetalleFactura
        
        Private eNTDatosOpcionalesField As ENTDatosOpcionales
        
        Private datosFacturadorManualField As DatosFacturadorManual
        
        Private claveCertificadoField As String
        
        Private nombreArchivoField As String
        
        Private eNTFacturaRetencionField() As ENTFacturaRetencion
        
        Private eNTFacturaRubroTerceroField() As ENTFacturaRubroTercero
        
        Private direccionPartidaField As String
        
        Private direccionDestinatarioField As String
        
        Private fechaInicioTransporteField As Date
        
        Private fechaFinTransporteField As Date
        
        Private razonSocialTransportistaField As String
        
        Private tipoIdentificacionTransportistaField As String
        
        Private identificacionTransportistaField As String
        
        Private placaField As String
        
        Private eNTFacturaGuiaRemisionDestinoField() As ENTFacturaGuiaRemisionDestino
        
        Private clsGenericXMLB64Field As String
        
        Private nombreIntegracionField As String
        
        Private ipField As String
        
        Private tipoNegociableCorreoField As String
        
        Private eNTMaquinaFiscalField As ENTMaquinaFiscal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Tipo() As System.Nullable(Of Integer)
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaCompensacion() As ENTCompensacion()
            Get
                Return Me.eNTFacturaCompensacionField
            End Get
            Set
                Me.eNTFacturaCompensacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaPagos() As ENTFacturaPagos()
            Get
                Return Me.eNTFacturaPagosField
            End Get
            Set
                Me.eNTFacturaPagosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaReembolso() As ENTFacturaReembolso()
            Get
                Return Me.eNTFacturaReembolsoField
            End Get
            Set
                Me.eNTFacturaReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ComercioExterior() As String
            Get
                Return Me.comercioExteriorField
            End Get
            Set
                Me.comercioExteriorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IncoTermFactura() As String
            Get
                Return Me.incoTermFacturaField
            End Get
            Set
                Me.incoTermFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LugarIncoTerm() As String
            Get
                Return Me.lugarIncoTermField
            End Get
            Set
                Me.lugarIncoTermField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PaisOrigen() As String
            Get
                Return Me.paisOrigenField
            End Get
            Set
                Me.paisOrigenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PuertoEmbarque() As String
            Get
                Return Me.puertoEmbarqueField
            End Get
            Set
                Me.puertoEmbarqueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PuertoDestino() As String
            Get
                Return Me.puertoDestinoField
            End Get
            Set
                Me.puertoDestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PaisDestino() As String
            Get
                Return Me.paisDestinoField
            End Get
            Set
                Me.paisDestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PaisAdquisicion() As String
            Get
                Return Me.paisAdquisicionField
            End Get
            Set
                Me.paisAdquisicionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirComprador() As String
            Get
                Return Me.dirCompradorField
            End Get
            Set
                Me.dirCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IncoTermTotalSinImpuestos() As String
            Get
                Return Me.incoTermTotalSinImpuestosField
            End Get
            Set
                Me.incoTermTotalSinImpuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FleteInternacional() As System.Nullable(Of Decimal)
            Get
                Return Me.fleteInternacionalField
            End Get
            Set
                Me.fleteInternacionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SeguroInternacional() As System.Nullable(Of Decimal)
            Get
                Return Me.seguroInternacionalField
            End Get
            Set
                Me.seguroInternacionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property GastosAduaneros() As System.Nullable(Of Decimal)
            Get
                Return Me.gastosAduanerosField
            End Get
            Set
                Me.gastosAduanerosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property GastosTransporteOtros() As System.Nullable(Of Decimal)
            Get
                Return Me.gastosTransporteOtrosField
            End Get
            Set
                Me.gastosTransporteOtrosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo1() As String
            Get
                Return Me.campo1Field
            End Get
            Set
                Me.campo1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo2() As String
            Get
                Return Me.campo2Field
            End Get
            Set
                Me.campo2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo3() As String
            Get
                Return Me.campo3Field
            End Get
            Set
                Me.campo3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo4() As String
            Get
                Return Me.campo4Field
            End Get
            Set
                Me.campo4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo5() As String
            Get
                Return Me.campo5Field
            End Get
            Set
                Me.campo5Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo6() As String
            Get
                Return Me.campo6Field
            End Get
            Set
                Me.campo6Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo7() As String
            Get
                Return Me.campo7Field
            End Get
            Set
                Me.campo7Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo8() As String
            Get
                Return Me.campo8Field
            End Get
            Set
                Me.campo8Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo9() As String
            Get
                Return Me.campo9Field
            End Get
            Set
                Me.campo9Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo10() As String
            Get
                Return Me.campo10Field
            End Get
            Set
                Me.campo10Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo11() As String
            Get
                Return Me.campo11Field
            End Get
            Set
                Me.campo11Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo12() As String
            Get
                Return Me.campo12Field
            End Get
            Set
                Me.campo12Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo13() As String
            Get
                Return Me.campo13Field
            End Get
            Set
                Me.campo13Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo14() As String
            Get
                Return Me.campo14Field
            End Get
            Set
                Me.campo14Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Campo15() As String
            Get
                Return Me.campo15Field
            End Get
            Set
                Me.campo15Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoTransaccionERP() As String
            Get
                Return Me.codigoTransaccionERPField
            End Get
            Set
                Me.codigoTransaccionERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioProceso() As String
            Get
                Return Me.usuarioProcesoField
            End Get
            Set
                Me.usuarioProcesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioTransaccionERP() As String
            Get
                Return Me.usuarioTransaccionERPField
            End Get
            Set
                Me.usuarioTransaccionERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFactura() As Long
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AutorizacionSRI() As String
            Get
                Return Me.autorizacionSRIField
            End Get
            Set
                Me.autorizacionSRIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaAutorizacion() As System.Nullable(Of Date)
            Get
                Return Me.fechaAutorizacionField
            End Get
            Set
                Me.fechaAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ambiente() As Integer
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoEmision() As Integer
            Get
                Return Me.tipoEmisionField
            End Get
            Set
                Me.tipoEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreComercial() As String
            Get
                Return Me.nombreComercialField
            End Get
            Set
                Me.nombreComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ruc() As String
            Get
                Return Me.rucField
            End Get
            Set
                Me.rucField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoDocumento() As String
            Get
                Return Me.codigoDocumentoField
            End Get
            Set
                Me.codigoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Establecimiento() As String
            Get
                Return Me.establecimientoField
            End Get
            Set
                Me.establecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PuntoEmision() As String
            Get
                Return Me.puntoEmisionField
            End Get
            Set
                Me.puntoEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Secuencial() As String
            Get
                Return Me.secuencialField
            End Get
            Set
                Me.secuencialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionMatriz() As String
            Get
                Return Me.direccionMatrizField
            End Get
            Set
                Me.direccionMatrizField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEmision() As Date
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                Me.fechaEmisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionEstablecimiento() As String
            Get
                Return Me.direccionEstablecimientoField
            End Get
            Set
                Me.direccionEstablecimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContribuyenteEspecial() As String
            Get
                Return Me.contribuyenteEspecialField
            End Get
            Set
                Me.contribuyenteEspecialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObligadoContabilidad() As String
            Get
                Return Me.obligadoContabilidadField
            End Get
            Set
                Me.obligadoContabilidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificacionComprador() As String
            Get
                Return Me.tipoIdentificacionCompradorField
            End Get
            Set
                Me.tipoIdentificacionCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GuiaRemision() As String
            Get
                Return Me.guiaRemisionField
            End Get
            Set
                Me.guiaRemisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocialComprador() As String
            Get
                Return Me.razonSocialCompradorField
            End Get
            Set
                Me.razonSocialCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionComprador() As String
            Get
                Return Me.identificacionCompradorField
            End Get
            Set
                Me.identificacionCompradorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalSinImpuesto() As Decimal
            Get
                Return Me.totalSinImpuestoField
            End Get
            Set
                Me.totalSinImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalSubsidio() As System.Nullable(Of Decimal)
            Get
                Return Me.totalSubsidioField
            End Get
            Set
                Me.totalSubsidioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalDescuento() As Decimal
            Get
                Return Me.totalDescuentoField
            End Get
            Set
                Me.totalDescuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodDocReemb() As String
            Get
                Return Me.codDocReembField
            End Get
            Set
                Me.codDocReembField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalComprobantesReembolso() As System.Nullable(Of Decimal)
            Get
                Return Me.totalComprobantesReembolsoField
            End Get
            Set
                Me.totalComprobantesReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalBaseImponibleReembolso() As System.Nullable(Of Decimal)
            Get
                Return Me.totalBaseImponibleReembolsoField
            End Get
            Set
                Me.totalBaseImponibleReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalImpuestoReembolso() As System.Nullable(Of Decimal)
            Get
                Return Me.totalImpuestoReembolsoField
            End Get
            Set
                Me.totalImpuestoReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Propina() As Decimal
            Get
                Return Me.propinaField
            End Get
            Set
                Me.propinaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImporteTotal() As Decimal
            Get
                Return Me.importeTotalField
            End Get
            Set
                Me.importeTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property valorRetIva() As System.Nullable(Of Decimal)
            Get
                Return Me.valorRetIvaField
            End Get
            Set
                Me.valorRetIvaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property valorRetRenta() As System.Nullable(Of Decimal)
            Get
                Return Me.valorRetRentaField
            End Get
            Set
                Me.valorRetRentaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As Integer
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecuencialERP() As String
            Get
                Return Me.secuencialERPField
            End Get
            Set
                Me.secuencialERPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaImpuesto() As ENTFacturaImpuesto()
            Get
                Return Me.eNTFacturaImpuestoField
            End Get
            Set
                Me.eNTFacturaImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatoAdicionalFactura() As ENTDatoAdicionalFactura()
            Get
                Return Me.eNTDatoAdicionalFacturaField
            End Get
            Set
                Me.eNTDatoAdicionalFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailResponsable() As String
            Get
                Return Me.emailResponsableField
            End Get
            Set
                Me.emailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaCarga() As String
            Get
                Return Me.fechaCargaField
            End Get
            Set
                Me.fechaCargaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDetalleFactura() As ENTDetalleFactura()
            Get
                Return Me.eNTDetalleFacturaField
            End Get
            Set
                Me.eNTDetalleFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatosOpcionales() As ENTDatosOpcionales
            Get
                Return Me.eNTDatosOpcionalesField
            End Get
            Set
                Me.eNTDatosOpcionalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatosFacturadorManual() As DatosFacturadorManual
            Get
                Return Me.datosFacturadorManualField
            End Get
            Set
                Me.datosFacturadorManualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveCertificado() As String
            Get
                Return Me.claveCertificadoField
            End Get
            Set
                Me.claveCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreArchivo() As String
            Get
                Return Me.nombreArchivoField
            End Get
            Set
                Me.nombreArchivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaRetencion() As ENTFacturaRetencion()
            Get
                Return Me.eNTFacturaRetencionField
            End Get
            Set
                Me.eNTFacturaRetencionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaRubroTercero() As ENTFacturaRubroTercero()
            Get
                Return Me.eNTFacturaRubroTerceroField
            End Get
            Set
                Me.eNTFacturaRubroTerceroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionPartida() As String
            Get
                Return Me.direccionPartidaField
            End Get
            Set
                Me.direccionPartidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DireccionDestinatario() As String
            Get
                Return Me.direccionDestinatarioField
            End Get
            Set
                Me.direccionDestinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaInicioTransporte() As Date
            Get
                Return Me.fechaInicioTransporteField
            End Get
            Set
                Me.fechaInicioTransporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaFinTransporte() As Date
            Get
                Return Me.fechaFinTransporteField
            End Get
            Set
                Me.fechaFinTransporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazonSocialTransportista() As String
            Get
                Return Me.razonSocialTransportistaField
            End Get
            Set
                Me.razonSocialTransportistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificacionTransportista() As String
            Get
                Return Me.tipoIdentificacionTransportistaField
            End Get
            Set
                Me.tipoIdentificacionTransportistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionTransportista() As String
            Get
                Return Me.identificacionTransportistaField
            End Get
            Set
                Me.identificacionTransportistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaGuiaRemisionDestino() As ENTFacturaGuiaRemisionDestino()
            Get
                Return Me.eNTFacturaGuiaRemisionDestinoField
            End Get
            Set
                Me.eNTFacturaGuiaRemisionDestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClsGenericXMLB64() As String
            Get
                Return Me.clsGenericXMLB64Field
            End Get
            Set
                Me.clsGenericXMLB64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreIntegracion() As String
            Get
                Return Me.nombreIntegracionField
            End Get
            Set
                Me.nombreIntegracionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IP() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoNegociableCorreo() As String
            Get
                Return Me.tipoNegociableCorreoField
            End Get
            Set
                Me.tipoNegociableCorreoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTMaquinaFiscal() As ENTMaquinaFiscal
            Get
                Return Me.eNTMaquinaFiscalField
            End Get
            Set
                Me.eNTMaquinaFiscalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTCompensacion
        
        Private codigoField As String
        
        Private tarifaField As String
        
        Private valorField As Decimal
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As String
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EComprobante
        
        Private claveAccesoField As String
        
        Private mensajesField() As EMensaje
        
        '''<remarks/>
        Public Property claveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensajes() As EMensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EMensaje
        
        Private identificadorField As String
        
        Private mensaje1Field As String
        
        Private informacionAdicionalField As String
        
        Private tipoField As String
        
        '''<remarks/>
        Public Property identificador() As String
            Get
                Return Me.identificadorField
            End Get
            Set
                Me.identificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje1() As String
            Get
                Return Me.mensaje1Field
            End Get
            Set
                Me.mensaje1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property informacionAdicional() As String
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                Me.informacionAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EAutorizacion
        
        Private estadoField As String
        
        Private numeroAutorizacionField As String
        
        Private claveAccesoField As String
        
        Private fechaAutorizacionField As Date
        
        Private fechaAutorizacionFieldSpecified As Boolean
        
        Private fechaAutorizacionSpecified1Field As Boolean
        
        Private ambienteField As String
        
        Private comprobanteField As String
        
        Private mensajesField() As EMensaje
        
        '''<remarks/>
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroAutorizacion() As String
            Get
                Return Me.numeroAutorizacionField
            End Get
            Set
                Me.numeroAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fechaAutorizacion() As Date
            Get
                Return Me.fechaAutorizacionField
            End Get
            Set
                Me.fechaAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaAutorizacionSpecified() As Boolean
            Get
                Return Me.fechaAutorizacionFieldSpecified
            End Get
            Set
                Me.fechaAutorizacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("fechaAutorizacionSpecified")>  _
        Public Property fechaAutorizacionSpecified1() As Boolean
            Get
                Return Me.fechaAutorizacionSpecified1Field
            End Get
            Set
                Me.fechaAutorizacionSpecified1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ambiente() As String
            Get
                Return Me.ambienteField
            End Get
            Set
                Me.ambienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comprobante() As String
            Get
                Return Me.comprobanteField
            End Get
            Set
                Me.comprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensajes() As EMensaje()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RespuestaEDOC
        
        Private claveAccesoField As String
        
        Private numeroComprobantesField As String
        
        Private estadoField As String
        
        Private autorizacionesField() As EAutorizacion
        
        Private comprobantesField() As EComprobante
        
        '''<remarks/>
        Public Property ClaveAcceso() As String
            Get
                Return Me.claveAccesoField
            End Get
            Set
                Me.claveAccesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroComprobantes() As String
            Get
                Return Me.numeroComprobantesField
            End Get
            Set
                Me.numeroComprobantesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property autorizaciones() As EAutorizacion()
            Get
                Return Me.autorizacionesField
            End Get
            Set
                Me.autorizacionesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comprobantes() As EComprobante()
            Get
                Return Me.comprobantesField
            End Get
            Set
                Me.comprobantesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTMaquinaFiscal
        
        Private marcaField As String
        
        Private modeloField As String
        
        Private serieField As String
        
        '''<remarks/>
        Public Property Marca() As String
            Get
                Return Me.marcaField
            End Get
            Set
                Me.marcaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Modelo() As String
            Get
                Return Me.modeloField
            End Get
            Set
                Me.modeloField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaGuiaRemisionDestino
        
        Private motivoTrasladoField As String
        
        Private docAduaneroUnicoField As String
        
        Private codEstabDestinoField As String
        
        Private rutaField As String
        
        '''<remarks/>
        Public Property MotivoTraslado() As String
            Get
                Return Me.motivoTrasladoField
            End Get
            Set
                Me.motivoTrasladoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocAduaneroUnico() As String
            Get
                Return Me.docAduaneroUnicoField
            End Get
            Set
                Me.docAduaneroUnicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodEstabDestino() As String
            Get
                Return Me.codEstabDestinoField
            End Get
            Set
                Me.codEstabDestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ruta() As String
            Get
                Return Me.rutaField
            End Get
            Set
                Me.rutaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaRubroTercero
        
        Private conceptoField As String
        
        Private totalField As Decimal
        
        '''<remarks/>
        Public Property Concepto() As String
            Get
                Return Me.conceptoField
            End Get
            Set
                Me.conceptoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaRetencion
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private tarifaField As Decimal
        
        Private valorField As Decimal
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Decimal
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DatosFacturadorManual
        
        Private facturadorManualField As Boolean
        
        Private usaDirectorioField As Integer
        
        '''<remarks/>
        Public Property FacturadorManual() As Boolean
            Get
                Return Me.facturadorManualField
            End Get
            Set
                Me.facturadorManualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaDirectorio() As Integer
            Get
                Return Me.usaDirectorioField
            End Get
            Set
                Me.usaDirectorioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatosOpcionales
        
        Private mailResponsableField As String
        
        Private usuarioCreadorField As String
        
        Private directorioDocumentoField As String
        
        Private nombreDocumentoField As String
        
        '''<remarks/>
        Public Property MailResponsable() As String
            Get
                Return Me.mailResponsableField
            End Get
            Set
                Me.mailResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioCreador() As String
            Get
                Return Me.usuarioCreadorField
            End Get
            Set
                Me.usuarioCreadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirectorioDocumento() As String
            Get
                Return Me.directorioDocumentoField
            End Get
            Set
                Me.directorioDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreDocumento() As String
            Get
                Return Me.nombreDocumentoField
            End Get
            Set
                Me.nombreDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDetalleFacturaImpuesto
        
        Private idDetalleFacturaImpuestoField As Long
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private baseImponibleField As Decimal
        
        Private tarifaField As Decimal
        
        Private valorField As Decimal
        
        Private idDetalleFacturaField As Long
        
        '''<remarks/>
        Public Property IdDetalleFacturaImpuesto() As Long
            Get
                Return Me.idDetalleFacturaImpuestoField
            End Get
            Set
                Me.idDetalleFacturaImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseImponible() As Decimal
            Get
                Return Me.baseImponibleField
            End Get
            Set
                Me.baseImponibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Decimal
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdDetalleFactura() As Long
            Get
                Return Me.idDetalleFacturaField
            End Get
            Set
                Me.idDetalleFacturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatoAdicionalDetalleFactura
        
        Private idDatoAdicionalDetalleFacturaField As Long
        
        Private nombreField As String
        
        Private descripcionField As String
        
        Private idDetalleFacturaField As Long
        
        '''<remarks/>
        Public Property IdDatoAdicionalDetalleFactura() As Long
            Get
                Return Me.idDatoAdicionalDetalleFacturaField
            End Get
            Set
                Me.idDatoAdicionalDetalleFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdDetalleFactura() As Long
            Get
                Return Me.idDetalleFacturaField
            End Get
            Set
                Me.idDetalleFacturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDetalleFactura
        
        Private idDetalleFacturaField As Long
        
        Private codigoPrincipalField As String
        
        Private codigoAuxiliarField As String
        
        Private descripcionField As String
        
        Private unidadMedidaField As String
        
        Private cantidadField As Decimal
        
        Private precioUnitarioField As Decimal
        
        Private precioSinSubsidioField As System.Nullable(Of Decimal)
        
        Private descuentoField As System.Nullable(Of Decimal)
        
        Private precioTotalSinImpuestoField As Decimal
        
        Private idFacturaField As Long
        
        Private eNTDatoAdicionalDetalleFacturaField() As ENTDatoAdicionalDetalleFactura
        
        Private eNTDetalleFacturaImpuestoField() As ENTDetalleFacturaImpuesto
        
        '''<remarks/>
        Public Property IdDetalleFactura() As Long
            Get
                Return Me.idDetalleFacturaField
            End Get
            Set
                Me.idDetalleFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPrincipal() As String
            Get
                Return Me.codigoPrincipalField
            End Get
            Set
                Me.codigoPrincipalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoAuxiliar() As String
            Get
                Return Me.codigoAuxiliarField
            End Get
            Set
                Me.codigoAuxiliarField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnidadMedida() As String
            Get
                Return Me.unidadMedidaField
            End Get
            Set
                Me.unidadMedidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioUnitario() As Decimal
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PrecioSinSubsidio() As System.Nullable(Of Decimal)
            Get
                Return Me.precioSinSubsidioField
            End Get
            Set
                Me.precioSinSubsidioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Descuento() As System.Nullable(Of Decimal)
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioTotalSinImpuesto() As Decimal
            Get
                Return Me.precioTotalSinImpuestoField
            End Get
            Set
                Me.precioTotalSinImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFactura() As Long
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDatoAdicionalDetalleFactura() As ENTDatoAdicionalDetalleFactura()
            Get
                Return Me.eNTDatoAdicionalDetalleFacturaField
            End Get
            Set
                Me.eNTDatoAdicionalDetalleFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTDetalleFacturaImpuesto() As ENTDetalleFacturaImpuesto()
            Get
                Return Me.eNTDetalleFacturaImpuestoField
            End Get
            Set
                Me.eNTDetalleFacturaImpuestoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTDatoAdicionalFactura
        
        Private idDatoAdicionalFacturaField As Long
        
        Private nombreField As String
        
        Private descripcionField As String
        
        Private idFacturaField As Long
        
        '''<remarks/>
        Public Property IdDatoAdicionalFactura() As Long
            Get
                Return Me.idDatoAdicionalFacturaField
            End Get
            Set
                Me.idDatoAdicionalFacturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFactura() As Long
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaImpuesto
        
        Private descuentoAdicionalField As System.Nullable(Of Decimal)
        
        Private idFacturaImpuestoField As Long
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private baseImponibleField As Decimal
        
        Private tarifaField As Decimal
        
        Private valorField As Decimal
        
        Private idFacturaField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DescuentoAdicional() As System.Nullable(Of Decimal)
            Get
                Return Me.descuentoAdicionalField
            End Get
            Set
                Me.descuentoAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFacturaImpuesto() As Long
            Get
                Return Me.idFacturaImpuestoField
            End Get
            Set
                Me.idFacturaImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseImponible() As Decimal
            Get
                Return Me.baseImponibleField
            End Get
            Set
                Me.baseImponibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Decimal
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdFactura() As Long
            Get
                Return Me.idFacturaField
            End Get
            Set
                Me.idFacturaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaReembolsoImpuesto
        
        Private idFacturaImpuestoField As Long
        
        Private codigoField As Integer
        
        Private codigoPorcentajeField As Integer
        
        Private baseImponibleReembolsoField As Decimal
        
        Private tarifaField As Long
        
        Private impuestoReembolsoField As Decimal
        
        Private idReembolsoField As Long
        
        '''<remarks/>
        Public Property IdFacturaImpuesto() As Long
            Get
                Return Me.idFacturaImpuestoField
            End Get
            Set
                Me.idFacturaImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPorcentaje() As Integer
            Get
                Return Me.codigoPorcentajeField
            End Get
            Set
                Me.codigoPorcentajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseImponibleReembolso() As Decimal
            Get
                Return Me.baseImponibleReembolsoField
            End Get
            Set
                Me.baseImponibleReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tarifa() As Long
            Get
                Return Me.tarifaField
            End Get
            Set
                Me.tarifaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImpuestoReembolso() As Decimal
            Get
                Return Me.impuestoReembolsoField
            End Get
            Set
                Me.impuestoReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdReembolso() As Long
            Get
                Return Me.idReembolsoField
            End Get
            Set
                Me.idReembolsoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaReembolso
        
        Private eNTFacturaReembolsoImpuestosField() As ENTFacturaReembolsoImpuesto
        
        Private eNTFacturaReembolsoCompensacionField() As ENTCompensacion
        
        Private idReembolsoField As Long
        
        Private tipoIdentificacionProveedorReembolsoField As String
        
        Private identificacionProveedorReembolsoField As String
        
        Private codPaisPagoProveedorReembolsoField As Integer
        
        Private tipoProveedorReembolsoField As String
        
        Private codDocReembolsoField As String
        
        Private estabDocReembolsoField As String
        
        Private ptoEmiDocReembolsoField As String
        
        Private secuencialDocReembolsoField As String
        
        Private fechaEmisionDocReembolsoField As Date
        
        Private numeroAutorizacionDocReembField As String
        
        '''<remarks/>
        Public Property ENTFacturaReembolsoImpuestos() As ENTFacturaReembolsoImpuesto()
            Get
                Return Me.eNTFacturaReembolsoImpuestosField
            End Get
            Set
                Me.eNTFacturaReembolsoImpuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTFacturaReembolsoCompensacion() As ENTCompensacion()
            Get
                Return Me.eNTFacturaReembolsoCompensacionField
            End Get
            Set
                Me.eNTFacturaReembolsoCompensacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdReembolso() As Long
            Get
                Return Me.idReembolsoField
            End Get
            Set
                Me.idReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificacionProveedorReembolso() As String
            Get
                Return Me.tipoIdentificacionProveedorReembolsoField
            End Get
            Set
                Me.tipoIdentificacionProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionProveedorReembolso() As String
            Get
                Return Me.identificacionProveedorReembolsoField
            End Get
            Set
                Me.identificacionProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodPaisPagoProveedorReembolso() As Integer
            Get
                Return Me.codPaisPagoProveedorReembolsoField
            End Get
            Set
                Me.codPaisPagoProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoProveedorReembolso() As String
            Get
                Return Me.tipoProveedorReembolsoField
            End Get
            Set
                Me.tipoProveedorReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodDocReembolso() As String
            Get
                Return Me.codDocReembolsoField
            End Get
            Set
                Me.codDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EstabDocReembolso() As String
            Get
                Return Me.estabDocReembolsoField
            End Get
            Set
                Me.estabDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PtoEmiDocReembolso() As String
            Get
                Return Me.ptoEmiDocReembolsoField
            End Get
            Set
                Me.ptoEmiDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecuencialDocReembolso() As String
            Get
                Return Me.secuencialDocReembolsoField
            End Get
            Set
                Me.secuencialDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaEmisionDocReembolso() As Date
            Get
                Return Me.fechaEmisionDocReembolsoField
            End Get
            Set
                Me.fechaEmisionDocReembolsoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroAutorizacionDocReemb() As String
            Get
                Return Me.numeroAutorizacionDocReembField
            End Get
            Set
                Me.numeroAutorizacionDocReembField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ENTFacturaPagos
        
        Private formaPagoField As String
        
        Private totalField As Decimal
        
        Private plazoField As System.Nullable(Of Integer)
        
        Private unidadTiempoField As String
        
        '''<remarks/>
        Public Property FormaPago() As String
            Get
                Return Me.formaPagoField
            End Get
            Set
                Me.formaPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Plazo() As System.Nullable(Of Integer)
            Get
                Return Me.plazoField
            End Get
            Set
                Me.plazoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnidadTiempo() As String
            Get
                Return Me.unidadTiempoField
            End Get
            Set
                Me.unidadTiempoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub EnviarFacturaSRICompletedEventHandler(ByVal sender As Object, ByVal e As EnviarFacturaSRICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarFacturaSRICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEDOC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEDOC)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub EnviarFacturaSRI_XMLCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarFacturaSRI_XMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarFacturaSRI_XMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaEDOC
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaEDOC)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
